
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * Greet someone by name - basic test command
 */
async greet(name: string) : Promise<string> {
    return await TAURI_INVOKE("greet", { name });
},
/**
 * Get the current application version
 */
async getVersion() : Promise<VersionInfo> {
    return await TAURI_INVOKE("get_version");
},
/**
 * Validate that a folder is a valid project (contains package.json or tsconfig.json)
 */
async validateProject(path: string) : Promise<ProjectValidation> {
    return await TAURI_INVOKE("validate_project", { path });
},
/**
 * Parse a single TSX component file and return component information
 */
async parseComponent(path: string) : Promise<Result<ComponentInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("parse_component", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Scan a directory for TSX components and return all found components
 */
async scanComponents(dir: string) : Promise<Result<ComponentInfo[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("scan_components", { dir }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Parse a CSS file and extract theme tokens from @theme blocks
 */
async parseTokens(cssPath: string) : Promise<Result<ThemeTokens, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("parse_tokens", { cssPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Scan a directory for design system violations
 */
async scanViolations(dir: string) : Promise<Result<ViolationInfo[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("scan_violations", { dir }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Detect violations in a single file
 */
async detectViolations(path: string) : Promise<Result<ViolationInfo[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("detect_violations", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Start watching a directory for file changes
 * Emits "file-changed" events to the frontend
 */
async startWatcher(path: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_watcher", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Stop the file watcher
 */
async stopWatcher() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_watcher") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get the currently watched path, if any
 */
async getWatchedPath() : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_watched_path") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Write a text change to a source file
 * 
 * This command reads the file, replaces the old text with new text at the specified line,
 * and writes the file back. It's designed for Text Edit Mode's direct write functionality.
 */
async writeTextChange(path: string, line: number, oldText: string, newText: string) : Promise<TextChangeResult> {
    return await TAURI_INVOKE("write_text_change", { path, line, oldText, newText });
},
/**
 * Get file information including modification time
 * 
 * Used to check if a file has been modified externally before writing.
 */
async getFileInfo(path: string) : Promise<FileInfo> {
    return await TAURI_INVOKE("get_file_info", { path });
},
/**
 * Revert a text change (for undo functionality)
 * 
 * This is essentially the same as write_text_change but with swapped old/new text.
 */
async revertTextChange(path: string, line: number, currentText: string, originalText: string) : Promise<TextChangeResult> {
    return await TAURI_INVOKE("revert_text_change", { path, line, currentText, originalText });
},
/**
 * Detect a project and extract its configuration
 */
async detectProject(path: string) : Promise<ProjectDetectionResult> {
    return await TAURI_INVOKE("detect_project", { path });
},
/**
 * Start the dev server for a project
 */
async startDevServer(path: string, command: string, port: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_dev_server", { path, command, port }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Stop the dev server
 */
async stopDevServer() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_dev_server") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get the current dev server status
 */
async getDevServerStatus() : Promise<Result<ServerStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_dev_server_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get recent dev server logs
 */
async getDevServerLogs() : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_dev_server_logs") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Check if the dev server is healthy (port responding)
 */
async checkDevServerHealth(port: number) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_dev_server_health", { port }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async scanDirectory(path: string, showHidden: boolean) : Promise<Result<DirectoryContents, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("scan_directory", { path, showHidden }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async expandFolder(path: string, showHidden: boolean) : Promise<Result<FileNode[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("expand_folder", { path, showHidden }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async searchFiles(root: string, query: string, maxResults: number, showHidden: boolean) : Promise<Result<SearchResults, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("search_files", { root, query, maxResults, showHidden }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Scan a theme package directory for component schemas and DNA configs
 */
async scanSchemas(path: string) : Promise<Result<ScanSchemasResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("scan_schemas", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Search schemas by component name with fuzzy matching
 */
async searchSchemas(path: string, query: string, maxResults: number) : Promise<Result<SchemaSearchResults, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("search_schemas", { path, query, maxResults }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get a single schema by component name
 */
async getSchema(path: string, componentName: string) : Promise<Result<ComponentSchema | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_schema", { path, componentName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get a single DNA config by component name
 */
async getDnaConfig(path: string, componentName: string) : Promise<Result<DnaConfig | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_dna_config", { path, componentName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Parse theme tokens from a theme directory (tokens.css + optional dark.css)
 */
async parseThemeTokensBundle(themePath: string) : Promise<Result<ThemeTokensBundle, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("parse_theme_tokens_bundle", { themePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Detect theme info from a theme directory path
 */
async detectThemeInfo(themePath: string) : Promise<Result<ThemeInfo | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("detect_theme_info", { themePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Scan a theme's assets directory and return the complete asset library
 */
async scanThemeAssets(themePath: string) : Promise<Result<AssetLibrary, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("scan_theme_assets", { themePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Scan a project's assets directory (separate from theme)
 */
async scanProjectAssets(projectPath: string) : Promise<Result<AssetLibrary, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("scan_project_assets", { projectPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Scan a monorepo root for themes and apps
 */
async scanMonorepo(root: string) : Promise<Result<MonorepoScanResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("scan_monorepo", { root }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async writeProxyTarget(config: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("write_proxy_target", { config }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async clearProxyTarget() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clear_proxy_target") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

/**
 * Complete asset library from a theme
 */
export type AssetLibrary = { icons: IconAsset[]; logos: LogoAsset[]; images: ImageAsset[] }
/**
 * Represents an extracted component with its metadata
 */
export type ComponentInfo = { name: string; file: string; line: number; props: PropInfo[]; defaultExport: boolean; unionTypes: UnionTypeInfo[] }
/**
 * Parsed component schema from *.schema.json files
 * Note: props and slots are stored as JSON strings for TypeScript compatibility
 */
export type ComponentSchema = { name: string; description: string; filePath: string; 
/**
 * JSON string containing prop definitions
 */
propsJson: string; 
/**
 * JSON string containing slot definitions
 */
slotsJson: string; examples: SchemaExample[]; subcomponents: string[] | null }
export type DirectoryContents = { path: string; children: FileNode[]; metadata: DirectoryMetadata }
export type DirectoryMetadata = { totalFiles: number; totalFolders: number; totalSize: number; readTimeMs: number }
/**
 * Parsed DNA configuration from *.dna.json files
 * Note: token_bindings and states are stored as JSON strings for TypeScript compatibility
 */
export type DnaConfig = { component: string; description: string | null; filePath: string; 
/**
 * JSON string containing token binding definitions
 */
tokenBindingsJson: string; 
/**
 * JSON string containing state definitions
 */
statesJson: string | null }
/**
 * Information about a file's current state
 */
export type FileInfo = { 
/**
 * File modification time (Unix timestamp in milliseconds)
 */
modifiedAt: number; 
/**
 * File exists
 */
exists: boolean }
export type FileNode = { id: string; name: string; path: string; nodeType: NodeType; extension: string | null; size: number; sizeFormatted: string; totalSize: number | null; childCount: number | null; modified: string; isHidden: boolean; isReadable: boolean; isAutoCollapsed: boolean }
/**
 * Represents an icon asset (always SVG)
 */
export type IconAsset = { 
/**
 * Unique ID (hash of path)
 */
id: string; 
/**
 * File name without extension
 */
name: string; 
/**
 * Relative path from theme root
 */
path: string; 
/**
 * Absolute path for loading
 */
absolutePath: string; 
/**
 * File size in bytes
 */
size: number; 
/**
 * Inline SVG content (read at scan time)
 */
content?: string | null }
/**
 * Represents an image asset
 */
export type ImageAsset = { id: string; name: string; path: string; absolutePath: string; size: number; 
/**
 * File extension (png, jpg, svg, etc.)
 */
extension: string; 
/**
 * Inline content: raw SVG string for .svg, base64 data URI for raster
 */
content?: string | null }
/**
 * Represents a logo asset
 */
export type LogoAsset = { id: string; name: string; path: string; absolutePath: string; size: number; 
/**
 * Inline content: raw SVG string for .svg, base64 data URI for raster
 */
content?: string | null }
/**
 * Entry representing an app discovered in a monorepo
 */
export type MonorepoAppEntry = { 
/**
 * Short ID (e.g., "rad-os")
 */
id: string; 
/**
 * Display name from package.json
 */
name: string; 
/**
 * Absolute path to app directory
 */
path: string; 
/**
 * Theme IDs this app depends on (resolved from @rdna/* deps)
 */
themeIds: string[]; 
/**
 * Dev command (e.g., "next dev")
 */
devCommand: string; 
/**
 * Dev server port
 */
devPort: number; 
/**
 * Preview route path (e.g., "/__component")
 */
previewRoute: string }
/**
 * Result of scanning a monorepo workspace
 */
export type MonorepoScanResult = { 
/**
 * Discovered theme packages
 */
themes: MonorepoThemeEntry[]; 
/**
 * Discovered app packages
 */
apps: MonorepoAppEntry[]; 
/**
 * Non-fatal errors encountered during scanning
 */
errors: string[] }
/**
 * Entry representing a theme package discovered in a monorepo
 */
export type MonorepoThemeEntry = { 
/**
 * Short ID (e.g., "radiants")
 */
id: string; 
/**
 * Display name from package.json
 */
name: string; 
/**
 * Absolute path to theme directory
 */
path: string; 
/**
 * Whether tokens.css exists
 */
hasTokensCss: boolean; 
/**
 * Whether dark.css exists
 */
hasDarkCss: boolean; 
/**
 * Whether components/ directory exists
 */
hasComponentsDir: boolean; 
/**
 * App IDs that depend on this theme
 */
apps: string[] }
export type NodeType = "File" | "Directory"
/**
 * Package manager detected from lockfile
 */
export type PackageManager = "pnpm" | "yarn" | "npm"
/**
 * Result of project detection
 */
export type ProjectDetectionResult = { success: boolean; project: ProjectInfo | null; error: string | null }
/**
 * Information about a detected project
 */
export type ProjectInfo = { path: string; name: string; projectType: ProjectType; packageManager: PackageManager; devCommand: string; devPort: number; nextVersion: string | null; hasBridge: boolean; 
/**
 * Resolved theme info (if project uses @rdna/* theme)
 */
theme: ThemeInfo | null; 
/**
 * Monorepo root path (if detected)
 */
monorepoRoot: string | null; 
/**
 * Whether this path is a theme package itself
 */
isTheme: boolean }
/**
 * Project type detected from dependencies
 */
export type ProjectType = "nextjs" | "unknown"
/**
 * Result of validating a project folder
 */
export type ProjectValidation = { valid: boolean; project_name: string | null; error: string | null }
/**
 * Represents a component prop with its type and optional default value
 */
export type PropInfo = { name: string; type: string; 
/**
 * Whether the prop is required (no default value and not optional)
 */
required: boolean; default?: string | null; doc?: string | null; 
/**
 * Inferred control type for UI: "text", "number", "boolean", "select", "slot"
 */
controlType?: string | null; 
/**
 * Options for select control (from union types)
 */
options?: string[] | null }
/**
 * Results from scanning a theme package for schemas
 */
export type ScanSchemasResult = { schemas: ComponentSchema[]; dnaConfigs: DnaConfig[]; totalSchemas: number; totalDnaConfigs: number; scanTimeMs: number }
/**
 * Example usage from a component schema
 */
export type SchemaExample = { name: string; code: string }
/**
 * Search match for fuzzy schema search
 */
export type SchemaSearchMatch = { schema: ComponentSchema; score: number; matchedIndices: number[] }
/**
 * Results from searching schemas
 */
export type SchemaSearchResults = { query: string; results: SchemaSearchMatch[]; totalMatches: number; searchTimeMs: number }
export type SearchMatch = { node: FileNode; score: number; matchedIndices: number[] }
export type SearchResults = { query: string; results: SearchMatch[]; totalMatches: number; truncated: boolean; searchTimeMs: number }
/**
 * Server state for display
 */
export type ServerStatus = { state: "stopped" } | { state: "starting"; logs: string[] } | { state: "running"; port: number; pid: number } | { state: "error"; message: string; logs: string[] }
/**
 * Result of a text change operation
 */
export type TextChangeResult = { 
/**
 * Whether the change was successfully written
 */
success: boolean; 
/**
 * Error message if failed
 */
error: string | null; 
/**
 * New file modification time (Unix timestamp in milliseconds)
 */
modifiedAt: number | null }
/**
 * Information about a detected theme package
 */
export type ThemeInfo = { 
/**
 * Theme package name (e.g., "radiants")
 */
name: string; 
/**
 * Full package name (e.g., "@rdna/radiants")
 */
packageName: string; 
/**
 * Absolute path to theme directory
 */
path: string; 
/**
 * Path to tokens.css file
 */
tokensCss: string; 
/**
 * Path to dark.css file (if exists)
 */
darkCss: string | null; 
/**
 * Path to components directory (if exists)
 */
componentsDir: string | null; 
/**
 * Path to assets directory (if exists)
 */
assetsDir: string | null }
/**
 * Theme tokens extracted from @theme blocks
 */
export type ThemeTokens = { 
/**
 * Tokens from @theme inline (internal reference, not exported as utilities)
 */
inline: Partial<{ [key in string]: string }>; 
/**
 * Tokens from @theme (exported as Tailwind utilities)
 */
public: Partial<{ [key in string]: string }> }
/**
 * Theme tokens bundle including both light and dark mode tokens
 */
export type ThemeTokensBundle = { 
/**
 * Base tokens from tokens.css (light mode)
 */
base: ThemeTokens; 
/**
 * Dark mode overrides from dark.css (if exists)
 */
dark: Partial<{ [key in string]: string }> | null }
/**
 * Represents a union type alias like `type ButtonVariant = 'primary' | 'secondary'`
 */
export type UnionTypeInfo = { name: string; values: string[]; line: number }
/**
 * Application version info returned by get_version command
 */
export type VersionInfo = { version: string; tauri_version: string }
/**
 * Represents a design system violation
 */
export type ViolationInfo = { file: string; line: number; column: number; severity: ViolationSeverity; message: string; codeSnippet: string; suggestion?: string | null }
/**
 * Violation severity levels
 */
export type ViolationSeverity = "warning" | "error"

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
