packages:
  - packages/*
  - tools/*
  - apps/*
  - templates/*

ignoredBuiltDependencies:
  - '@stellar/stellar-sdk'
  - bigint-buffer
  - blake-hash
  - bufferutil
  - esbuild
  - keccak
  - protobufjs
  - secp256k1
  - sharp
  - tiny-secp256k1
  - unrs-resolver
  - usb
  - utf-8-validate
