/**
 * @rdna/radiants ESLint token map
 *
 * Re-exports all ESLint rule data from the generated design contract.
 * Source of truth: packages/radiants/generated/eslint-contract.json
 * Generated by: pnpm registry:generate (extends the same pipeline as registry.manifest.json)
 *
 * If the contract file is missing (pre-generation or CI cold start), this module
 * falls back to the hand-authored values preserved below so lint never hard-crashes.
 */

import { createRequire } from 'module';

const require = createRequire(import.meta.url);

// ---------------------------------------------------------------------------
// Load generated contract
// ---------------------------------------------------------------------------

let contract = null;

try {
  contract = require('../generated/eslint-contract.json');
} catch (err) {
  if (err.code !== 'MODULE_NOT_FOUND' && !(err instanceof SyntaxError)) {
    throw err;
  }
  // Fall through — hand-authored fallbacks are used below.
}

// ---------------------------------------------------------------------------
// Original exports (consumed by existing rules — interface must not change)
// ---------------------------------------------------------------------------

/** Brand palette — raw hex values keyed by lowercase hex. */
export const brandPalette =
  contract?.tokenMap?.brandPalette ??
  /* fallback — keep in sync with tokens.css */ {
    '#fef8e2': 'cream',
    '#0f0e0c': 'ink',
    '#000000': 'pure-black',
    '#fce184': 'sun-yellow',
    '#95bad2': 'sky-blue',
    '#fcc383': 'sunset-fuzz',
    '#ff6b63': 'sun-red',
    '#cef5ca': 'mint',
    '#ffffff': 'pure-white',
    '#22c55e': 'success-mint',
  };

/** Hex → semantic token mapping, keyed by Tailwind prefix context. */
export const hexToSemantic =
  contract?.tokenMap?.hexToSemantic ??
  /* fallback */ {
    '#fef8e2': { bg: 'page', text: 'flip' },
    '#0f0e0c': { bg: 'inv', text: 'main', border: 'line' },
    '#95bad2': { text: 'link' },
    '#ff6b63': { bg: 'danger', text: 'danger' },
    '#cef5ca': { bg: 'success', text: 'success' },
    '#ffffff': { bg: 'card' },
    '#22c55e': { text: 'success' },
  };

/** OKLCH → semantic token mapping, keyed by Tailwind prefix context. */
export const oklchToSemantic =
  contract?.tokenMap?.oklchToSemantic ??
  /* fallback */ {
    'oklch(0.9780 0.0295 94.34)': { bg: 'surface-primary', text: 'content-inverted' },
    'oklch(0.1641 0.0044 84.59)': { bg: 'surface-secondary', text: 'content-primary', border: 'edge-primary' },
    'oklch(0.9126 0.1170 93.68)': { bg: 'action-primary', border: 'edge-focus', ring: 'edge-focus' },
    'oklch(0.7701 0.0527 236.81)': { text: 'content-link' },
    'oklch(0.8546 0.1039 68.93)': { bg: 'action-accent' },
    'oklch(0.7102 0.1823 25.87)': { bg: 'action-destructive', text: 'status-error' },
    'oklch(0.9312 0.0702 142.51)': { bg: 'status-success', text: 'status-success' },
    'oklch(1.0000 0.0000 0)': { bg: 'surface-elevated' },
    'oklch(0.7227 0.1920 149.58)': { text: 'status-success' },
  };

/** Removed aliases — MUST NOT appear anywhere. */
export const removedAliases =
  contract?.tokenMap?.removedAliases ??
  /* fallback */ [
    '--color-black',
    '--color-white',
    '--color-green',
    '--color-success-green',
    '--glow-green',
  ];

/** RDNA components and the raw HTML elements they replace. */
export const rdnaComponentMap =
  contract?.componentMap ??
  /* fallback */ {
    button:   { component: 'Button',      import: '@rdna/radiants/components/core' },
    input:    { component: 'Input',       import: '@rdna/radiants/components/core', note: 'Only enforce for text-like input types in v1' },
    select:   { component: 'Select',      import: '@rdna/radiants/components/core' },
    textarea: { component: 'Input',       import: '@rdna/radiants/components/core', note: 'Use Input with multiline' },
    dialog:   { component: 'Dialog',      import: '@rdna/radiants/components/core' },
    details:  { component: 'Collapsible', import: '@rdna/radiants/components/core' },
    summary:  { component: 'Collapsible', import: '@rdna/radiants/components/core', note: 'Use Collapsible trigger' },
    label:    { component: 'Label',       import: '@rdna/radiants/components/core' },
    meter:    { component: 'Meter',       import: '@rdna/radiants/components/core' },
    progress: { component: 'Meter',       import: '@rdna/radiants/components/core', note: 'Use Meter for progress indicators' },
    hr:       { component: 'Separator',   import: '@rdna/radiants/components/core' },
  };

// ---------------------------------------------------------------------------
// New contract exports (consumed by refactored / new rules)
// ---------------------------------------------------------------------------

/** Valid semantic color token suffixes. Used by no-hardcoded-colors. */
export const semanticColorSuffixes =
  contract?.tokenMap?.semanticColorSuffixes ?? [
    'page', 'card', 'tinted', 'inv', 'depth', 'hover', 'active',
    'main', 'sub', 'mute', 'flip', 'head', 'link',
    'line', 'rule', 'line-hover', 'focus',
    'accent', 'accent-inv', 'accent-soft', 'danger',
    'success', 'warning',
    'window-chrome-from', 'window-chrome-to',
    'surface-primary', 'surface-secondary', 'surface-elevated',
    'content-primary', 'content-inverted', 'content-link',
    'action-primary', 'action-accent', 'action-destructive',
    'edge-primary', 'edge-focus',
    'status-success', 'status-error',
  ];

/** CSS classes that opt into clip-path pixel corners. Used by no-clipped-shadow, no-pixel-border. */
export const pixelCornerTriggerClasses =
  contract?.pixelCorners?.triggerClasses ?? [
    'pixel-corners',
    'pixel-rounded-xs', 'pixel-rounded-sm', 'pixel-rounded-md',
    'pixel-rounded-lg', 'pixel-rounded-xl',
  ];

/** Shadow migration map: box-shadow token → pixel-shadow suggestion. Used by no-clipped-shadow. */
export const shadowMigrationMap =
  contract?.pixelCorners?.shadowMigrationMap ?? {
    'shadow-surface':      'pixel-shadow-surface',
    'shadow-resting':      'pixel-shadow-resting',
    'shadow-lifted':       'pixel-shadow-lifted',
    'shadow-raised':       'pixel-shadow-raised',
    'shadow-floating':     'pixel-shadow-floating',
    'shadow-focused':      'pixel-shadow-floating (or custom filter: drop-shadow)',
    'shadow-glow-success': 'custom filter: drop-shadow with success color',
    'shadow-glow-error':   'custom filter: drop-shadow with error color',
    'shadow-glow-info':    'custom filter: drop-shadow with info color',
  };

/** Theme variant values targeted by theme CSS. Used by no-mixed-style-authority. */
export const themeVariants =
  contract?.themeVariants ?? [
    'default', 'raised', 'inverted',
    'select', 'switch', 'accordion',
    'success', 'warning', 'error', 'info',
  ];

/** Valid shadow token names. Used by no-raw-shadow, no-clipped-shadow. */
export const shadowTokens =
  contract?.shadows?.validStandard ?? [
    'shadow-surface', 'shadow-resting', 'shadow-lifted', 'shadow-raised',
    'shadow-floating', 'shadow-focused', 'shadow-inset',
    'shadow-btn', 'shadow-btn-hover', 'shadow-card', 'shadow-card-lg', 'shadow-inner',
  ];

/** Valid typography size steps. Used by no-hardcoded-typography. */
export const typographyTokens =
  contract?.typography?.validSizes ?? [
    'text-xs', 'text-sm', 'text-base', 'text-lg', 'text-xl', 'text-2xl', 'text-3xl',
  ];

/** Input types that are "text-like" (trigger prefer-rdna-components). */
export const textLikeInputTypes =
  contract?.textLikeInputTypes ?? [
    'text', 'email', 'password', 'search', 'url', 'tel', 'number',
  ];
