/**
 * AUTO-GENERATED — DO NOT EDIT
 *
 * Generated by: scripts/generate-icons.mjs
 * Source:       assets/icons/*.svg (153 icons)
 *
 * To regenerate: pnpm generate:icons
 */

import type { ReactElement } from 'react';
import type { IconProps } from './types';

export const USDC = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M1,6H2V4H3V3H4V2H6V1H10V2H12V3H13V4H14V6H15V10H14V12H13V13H12V14H10V15H6V14H4V13H3V12H2V10H1V6ZM3,6V10H4V6H3ZM4,5V6H5V5H4ZM4,10V11H5V10H4ZM5,4V5H6V4H5ZM5,11V12H6V11H5ZM6,3V4H7V3H6ZM6,6V8H8V7H7V6H6ZM6,9V10H7V9H6ZM6,12V13H8V12H6ZM7,4V6H9V5H8V4H7ZM7,10V11H8V12H9V10H7ZM8,3V4H10V3H8ZM8,8V9H9V10H10V8H8ZM9,6V7H10V6H9ZM9,12V13H10V12H9ZM10,4V5H11V4H10ZM10,11V12H11V11H10ZM11,5V6H12V5H11ZM11,10V11H12V10H11ZM12,6V10H13V6H12Z"/>
  </svg>
);
USDC.displayName = 'USDC';

export const BroadcastDish = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M2,13H3V12H4V13H5V14H2V13ZM3,6H4V5H5V7H6V8H7V9H8V10H9V11H11V12H10V13H5V12H4V11H3V6ZM8,2H12V3H8V2ZM8,7H9V8H8V7ZM9,4H11V5H9V4ZM9,6H10V7H9V6ZM11,5H12V7H11V5ZM12,3H13V4H12V3ZM13,4H14V8H13V4Z"/>
  </svg>
);
BroadcastDish.displayName = 'BroadcastDish';

export const BrokenBattery = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M5,4H6V6H5V4ZM5,9H6V13H5V9ZM6,3H7V2H9V3H10V4H6V3ZM6,6H7V5H10V6H9V7H8V8H10V9H9V10H8V9H6V6ZM6,13H10V14H6V13ZM7,10H8V11H7V10ZM10,4H11V5H10V4ZM10,6H11V8H10V6ZM10,9H11V13H10V9Z"/>
  </svg>
);
BrokenBattery.displayName = 'BrokenBattery';

export const Calendar = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M2,2H13V14H2V2ZM3,3V4H12V3H3ZM3,5V7H6V5H3ZM3,8V10H6V8H3ZM3,11V13H6V11H3ZM7,5V7H9V5H7ZM7,8V10H9V8H7ZM7,11V13H9V11H7ZM10,5V7H12V5H10ZM10,8V10H12V8H10ZM10,11V13H12V11H10Z"/>
  </svg>
);
Calendar.displayName = 'Calendar';

export const Calendar2 = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M1,2H14V14H1V2ZM2,3V5H13V3H2ZM2,6V7H3V6H2ZM2,8V9H3V8H2ZM2,10V11H3V10H2ZM2,12V13H3V12H2ZM4,6V7H5V6H4ZM4,8V9H5V8H4ZM4,10V11H5V10H4ZM4,12V13H5V12H4ZM6,6V7H7V6H6ZM6,8V9H7V8H6ZM6,10V11H7V10H6ZM6,12V13H7V12H6ZM8,6V7H9V6H8ZM8,8V9H9V8H8ZM8,10V11H9V10H8ZM8,12V13H9V12H8ZM10,6V7H11V6H10ZM10,8V9H11V8H10ZM10,10V11H11V10H10ZM10,12V13H11V12H10ZM12,6V7H13V6H12ZM12,8V9H13V8H12ZM12,10V11H13V10H12ZM12,12V13H13V12H12Z"/>
  </svg>
);
Calendar2.displayName = 'Calendar2';

export const Camera = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M1,6H2V5H3V4H5V5H6V6H5V7H1V6ZM3,5V6H4V5H3ZM1,8H4V10H5V11H6V12H2V11H1V8ZM5,7H6V10H5V7ZM6,6H7V7H6V6ZM6,10H7V11H6V10ZM7,5H10V6H7V5ZM7,11H10V12H7V11ZM8,8H9V9H8V8ZM10,6H11V7H10V6ZM10,10H11V11H10V10ZM11,5H13V6H14V7H12V6H11V5ZM11,7H12V10H11V7ZM11,11H12V10H13V8H14V11H13V12H11V11Z"/>
  </svg>
);
Camera.displayName = 'Camera';

export const CdHorizontal = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M2,7H3V9H2V7ZM3,6H5V5H11V6H13V7H12V8H11V9H9V10H11V11H5V10H3V9H4V7H3V6ZM5,6V7H6V6H5ZM7,7V8H9V7H7ZM7,9V10H8V9H7ZM11,9H13V10H11V9ZM13,7H14V9H13V7Z"/>
  </svg>
);
CdHorizontal.displayName = 'CdHorizontal';

export const Cd = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M2,6H3V10H2V6ZM3,4H4V3H6V2H10V3H12V4H13V6H12V10H13V12H12V13H10V14H6V13H4V12H3V10H4V6H3V4ZM11,5V4H10V5H11ZM12,6V5H11V6H12ZM12,10H11V11H12V10ZM5,11V12H6V11H5ZM4,10V11H5V10H4ZM4,6H5V5H4V6ZM5,7V9H6V7H5ZM6,6V7H7V6H6ZM6,9V10H7V9H6ZM7,5V6H9V5H7ZM7,7V9H9V7H7ZM7,10V11H9V10H7ZM9,6V7H10V6H9ZM9,9V10H10V9H9ZM10,7V9H11V7H10ZM13,6H14V10H13V6Z"/>
  </svg>
);
Cd.displayName = 'Cd';

export const CellBars = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M2,9H4V13H2V9ZM5,7H7V13H5V7ZM8,5H10V13H8V5ZM11,3H13V13H11V3Z"/>
  </svg>
);
CellBars.displayName = 'CellBars';

export const Checkmark = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M2,8H4V9H5V10H7V9H8V8H9V7H10V6H11V5H12V4H14V6H13V7H12V8H11V9H10V10H9V11H8V12H7V13H5V12H4V11H3V10H2V8Z"/>
  </svg>
);
Checkmark.displayName = 'Checkmark';

export const ChevronDown = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M1,6H3V7H4V8H5V9H6V10H7V11H9V10H10V9H11V8H12V7H13V6H15V8H14V9H13V10H12V11H11V12H10V13H9V14H7V13H6V12H5V11H4V10H3V9H2V8H1V6Z"/>
  </svg>
);
ChevronDown.displayName = 'ChevronDown';

export const ChevronLeft = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M10,1H8V2H7V3H6V4H5V5H4V6H3V7H2V9H3V10H4V11H5V12H6V13H7V14H8V15H10V13H9V12H8V11H7V10H6V9H5V7H6V6H7V5H8V4H9V3H10V1Z"/>
  </svg>
);
ChevronLeft.displayName = 'ChevronLeft';

export const ChevronRight = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M6,1H8V3H7V4H8V5H9V6H10V7H11V9H10V10H9V11H8V12H7V13H8V15H6V14H7V13H8V12H9V11H10V10H11V9H12V7H11V6H10V5H9V4H8V3H7V2H6V1Z"/>
  </svg>
);
ChevronRight.displayName = 'ChevronRight';

export const Clock = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M1,6H2V4H3V3H4V2H6V1H9V2H11V3H12V4H13V6H14V9H13V11H12V12H11V13H9V14H6V13H4V12H3V11H2V9H1V6ZM3,5V10H4V11H5V12H10V11H11V10H12V5H11V4H10V3H5V4H4V5H3ZM7,4H8V7H10V8H7V4Z"/>
  </svg>
);
Clock.displayName = 'Clock';

export const CloseFilled = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M1,6H2V4H3V3H4V2H6V1H10V2H12V3H13V4H14V6H15V10H14V12H13V13H12V14H10V15H6V14H4V13H3V12H2V10H1V6ZM4,4V6H5V7H6V9H5V10H4V12H6V11H7V10H9V11H10V12H12V10H11V9H10V7H11V6H12V4H10V5H9V6H7V5H6V4H4Z"/>
  </svg>
);
CloseFilled.displayName = 'CloseFilled';

export const Close = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M3,4H5V5H6V6H7V7H9V6H10V5H11V4H13V6H12V7H11V8H10V10H11V11H12V12H13V14H11V13H10V12H9V11H7V12H6V13H5V14H3V12H4V11H5V10H6V8H5V7H4V6H3V4Z"/>
  </svg>
);
Close.displayName = 'Close';

export const CodeFile = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M3,2H10V3H9V6H12V5H13V7H8V3H4V13H12V12H13V14H3V2ZM5,9H6V10H5V9ZM6,8H7V9H6V8ZM6,10H7V11H6V10ZM8,10H9V11H8V10ZM9,9H10V10H9V9ZM10,3H11V4H10V3ZM10,8H11V9H10V8ZM11,4H12V5H11V4ZM12,8H13V9H12V8ZM12,10H13V11H12V10ZM13,9H14V10H13V9Z"/>
  </svg>
);
CodeFile.displayName = 'CodeFile';

export const CodeFolder = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M1,4H2V12H1V4ZM2,3H5V4H2V3ZM2,12H14V13H2V12ZM4,9H5V10H4V9ZM5,4H14V5H5V4ZM5,8H6V9H5V8ZM5,10H6V11H5V10ZM7,10H8V11H7V10ZM8,9H9V10H8V9ZM9,8H10V9H9V8ZM11,8H12V9H11V8ZM11,10H12V11H11V10ZM12,9H13V10H12V9ZM14,5H15V12H14V5Z"/>
  </svg>
);
CodeFolder.displayName = 'CodeFolder';

export const CodeWindowFilled = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M1,5H2V4H14V5H15V13H14V14H2V13H1V5ZM4,7V8H5V7H4ZM4,11V12H5V11H4ZM5,8V9H6V8H5ZM5,10V11H6V10H5ZM6,9V10H7V9H6ZM8,5V6H9V5H8ZM8,11V12H12V11H8ZM10,5V6H11V5H10ZM12,5V6H13V5H12Z"/>
  </svg>
);
CodeWindowFilled.displayName = 'CodeWindowFilled';

export const CodeWindow = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M1,3H15V14H1V3ZM2,4V5H10V4H2ZM2,6V13H14V6H2ZM11,4V5H12V4H11ZM13,4V5H14V4H13ZM4,7H5V8H4V7ZM4,11H5V12H4V11ZM5,8H6V9H5V8ZM5,10H6V11H5V10ZM6,9H7V10H6V9ZM8,11H12V12H8V11Z"/>
  </svg>
);
CodeWindow.displayName = 'CodeWindow';

export const Coins = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M2,4H3V5H5V6H10V5H11V6H12V7H10V8H5V7H3V6H2V4ZM2,7H3V8H5V9H10V8H11V9H12V10H10V11H5V10H3V9H2V7ZM2,10H3V11H5V12H10V11H11V12H12V13H10V14H5V13H3V12H2V10ZM3,3H5V4H3V3ZM5,2H10V3H5V2ZM10,3H12V4H10V3ZM12,4H13V6H12V4ZM12,7H13V9H12V7ZM12,10H13V12H12V10Z"/>
  </svg>
);
Coins.displayName = 'Coins';

export const CommentsBlank = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M2,13H3V14H2V13ZM3,11H4V4H5V3H13V4H14V11H13V12H5V13H3V11Z"/>
  </svg>
);
CommentsBlank.displayName = 'CommentsBlank';

export const CommentsTyping = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M2,13H3V14H2V13ZM3,11H4V4H5V3H13V4H14V11H13V12H5V13H3V11ZM5,7V8H6V7H5ZM7,7V8H8V7H7ZM9,7V8H10V7H9ZM11,7V8H12V7H11Z"/>
  </svg>
);
CommentsTyping.displayName = 'CommentsTyping';

export const Computer = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M1,2H2V1H13V2H10V3H9V2H3V3H2V9H3V10H9V9H10V11H9V12H8V11H7V12H6V11H5V12H4V11H3V12H2V11H1V2ZM1,13H10V15H9V14H8V15H1V13ZM3,3H7V4H6V5H5V6H4V7H3V3ZM3,8H4V7H5V6H6V5H7V4H8V3H9V5H8V6H7V7H6V8H5V9H3V8ZM7,8H8V7H9V9H7V8ZM10,3H11V9H10V3ZM10,11H12V12H10V11ZM11,13H15V15H11V13ZM12,10H14V11H12V10ZM13,2H14V3H13V2ZM14,3H15V10H14V3Z"/>
  </svg>
);
Computer.displayName = 'Computer';

export const CopiedToClipboard = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M2,3H3V13H2V3ZM3,2H5V3H3V2ZM3,13H12V14H3V13ZM4,5H11V6H5V11H7V12H4V5ZM5,1H10V2H9V3H10V4H5V3H6V2H5V1ZM6,8H7V9H6V8ZM7,9H8V10H7V9ZM8,10H9V11H8V10ZM9,9H10V10H9V9ZM10,2H12V3H10V2ZM10,8H11V9H10V8ZM10,11H11V12H10V11ZM11,7H12V8H11V7ZM12,3H13V5H12V3ZM12,6H13V7H12V6ZM12,8H13V13H12V8ZM13,5H14V6H13V5Z"/>
  </svg>
);
CopiedToClipboard.displayName = 'CopiedToClipboard';

export const CopyToClipboard = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M3,4H4V13H12V4H13V14H3V4ZM4,3H5V4H4V3ZM5,5H6V6H10V5H11V12H5V5ZM6,7V8H10V7H6ZM6,9V10H10V9H6ZM6,3H7V4H9V3H10V5H6V3ZM7,2H9V3H7V2ZM11,3H12V4H11V3Z"/>
  </svg>
);
CopyToClipboard.displayName = 'CopyToClipboard';

export const Copy = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M3,3H4V13H13V14H3V3ZM5,2H10V6H14V12H5V2ZM11,2H12V3H13V4H14V5H11V2Z"/>
  </svg>
);
Copy.displayName = 'Copy';

export const Crosshair3 = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M2,7H5V8H2V7ZM4,4H5V5H4V4ZM4,10H5V11H4V10ZM7,2H8V5H7V2ZM7,7H8V8H7V7ZM7,10H8V13H7V10ZM10,4H11V5H10V4ZM10,7H13V8H10V7ZM10,10H11V11H10V10Z"/>
  </svg>
);
Crosshair3.displayName = 'Crosshair3';

export const Crosshair1 = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M1,7H4V9H1V7ZM2,4H3V6H2V4ZM2,10H3V12H2V10ZM3,3H4V4H3V3ZM3,12H4V13H3V12ZM4,2H6V3H4V2ZM4,13H6V14H4V13ZM7,1H9V4H7V1ZM7,7H9V9H7V7ZM7,12H9V15H7V12ZM10,2H12V3H10V2ZM10,13H12V14H10V13ZM12,3H13V4H12V3ZM12,7H15V9H12V7ZM12,12H13V13H12V12ZM13,4H14V6H13V4ZM13,10H14V12H13V10Z"/>
  </svg>
);
Crosshair1.displayName = 'Crosshair1';

export const Crosshair2Retro = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M3,6H6V3H7V7H3V6ZM3,9H7V13H6V10H3V9ZM9,3H10V6H13V7H9V3ZM9,9H13V10H10V13H9V9Z"/>
  </svg>
);
Crosshair2Retro.displayName = 'Crosshair2Retro';

export const Crosshair2 = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M2,7H5V9H2V7ZM7,2H9V5H7V2ZM7,7H9V9H7V7ZM7,11H9V14H7V11ZM11,7H14V9H11V7Z"/>
  </svg>
);
Crosshair2.displayName = 'Crosshair2';

export const Crosshair4 = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M2,8H3V9H2V8ZM4,8H6V7H7V4H8V7H9V8H11V9H9V10H8V13H7V10H6V9H4V8ZM7,8V9H8V8H7ZM7,2H8V3H7V2ZM7,14H8V15H7V14ZM12,8H13V9H12V8Z"/>
  </svg>
);
Crosshair4.displayName = 'Crosshair4';

export const CursorText = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M3,2H6V3H3V2ZM3,13H6V14H3V13ZM6,3H9V4H8V12H9V13H6V12H7V4H6V3ZM9,2H12V3H9V2ZM9,13H12V14H9V13Z"/>
  </svg>
);
CursorText.displayName = 'CursorText';

export const Cursor2 = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M4,1H5V2H6V3H7V4H8V5H9V6H10V7H11V8H12V9H9V11H10V13H11V15H9V14H8V12H7V10H6V11H5V12H4V1Z"/>
  </svg>
);
Cursor2.displayName = 'Cursor2';

export const Cursors1 = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M3,1H5V2H7V3H9V4H11V6H10V7H9V9H10V11H11V13H12V15H10V14H9V12H8V10H7V9H6V10H5V11H3V1Z"/>
  </svg>
);
Cursors1.displayName = 'Cursors1';

export const Cut = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M2,7H3V9H2V7ZM3,6H5V7H3V6ZM3,9H5V10H3V9ZM5,7H8V8H9V11H7V10H8V9H7V8H6V9H5V7ZM6,11H7V13H6V11ZM7,13H9V14H7V13ZM8,3H9V2H10V5H9V6H8V3ZM9,6H14V7H13V8H9V6ZM9,11H10V13H9V11Z"/>
  </svg>
);
Cut.displayName = 'Cut';

export const Discord = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="-2 -1 24 20" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M18 6V2H16V0H12V2H14V4H6V2H8V0H4V2H2V6H0V16H2V18H8V16H12V18H18V16H20V6H18ZM6 12V8H8V12H6ZM14 12H12V8H14V12Z"/>
  </svg>
);
Discord.displayName = 'Discord';

export const DocumentImage = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M3,2H9V6H13V14H3V2ZM4,9V12H12V10H11V9H10V8H9V9H8V8H7V7H6V8H5V9H4ZM5,4V6H7V4H5ZM7,10V11H6V10H7ZM8,9V10H7V9H8ZM10,2H11V3H12V4H13V5H10V2Z"/>
  </svg>
);
DocumentImage.displayName = 'DocumentImage';

export const Document = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M3,2H9V6H13V14H3V2ZM5,5V6H8V5H5ZM5,7V8H11V7H5ZM5,9V10H11V9H5ZM5,11V12H11V11H5ZM10,2H11V3H12V4H13V5H10V2Z"/>
  </svg>
);
Document.displayName = 'Document';

export const Document2 = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M3,2H11V3H10V5H12V4H13V14H3V2ZM4,3V13H12V6H9V3H4ZM11,3H12V4H11V3Z"/>
  </svg>
);
Document2.displayName = 'Document2';

export const Download = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M2,9H3V12H4V13H12V12H13V9H14V13H13V14H3V13H2V9ZM5,8H7V2H9V8H11V9H10V10H9V11H7V10H6V9H5V8Z"/>
  </svg>
);
Download.displayName = 'Download';

export const Eject = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M3,8H4V7H5V6H6V5H7V4H8V5H9V6H10V7H11V8H12V10H3V8ZM3,12H12V13H3V12Z"/>
  </svg>
);
Eject.displayName = 'Eject';

export const Electric = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M4,7H5V5H6V3H7V2H12V4H11V5H10V6H9V7H12V9H11V10H10V11H9V12H8V13H7V14H6V12H7V10H8V9H4V7Z"/>
  </svg>
);
Electric.displayName = 'Electric';

export const EnvelopeClosed = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M2,5H14V6H12V7H10V8H9V9H7V8H6V7H4V6H2V5ZM2,7H4V8H6V9H5V10H4V11H3V12H2V7ZM4,11H5V10H6V9H7V10H9V9H10V10H11V11H12V12H4V11ZM10,8H12V7H14V12H13V11H12V10H11V9H10V8Z"/>
  </svg>
);
EnvelopeClosed.displayName = 'EnvelopeClosed';

export const EnvelopeOpen = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M2,6H4V5H6V4H7V3H9V4H10V5H12V6H14V7H2V6ZM2,8H4V9H6V10H5V11H4V12H3V13H2V8ZM4,12H5V11H6V10H7V9H9V10H10V11H11V12H12V13H4V12ZM10,9H12V8H14V13H13V12H12V11H11V10H10V9Z"/>
  </svg>
);
EnvelopeOpen.displayName = 'EnvelopeOpen';

export const Equalizer = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M2,6H3V7H2V6ZM2,8H3V13H2V8ZM4,4H5V5H4V4ZM4,6H5V13H4V6ZM6,8H7V9H6V8ZM6,10H7V13H6V10ZM8,10H9V13H8V10ZM10,6H11V7H10V6ZM10,8H11V13H10V8ZM12,4H13V5H12V4ZM12,6H13V13H12V6Z"/>
  </svg>
);
Equalizer.displayName = 'Equalizer';

export const EyeHidden = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M1,8H2V9H1V8ZM2,7H3V8H2V7ZM2,9H3V10H2V9ZM3,6H5V7H3V6ZM3,10H5V11H3V10ZM4,13H5V14H4V13ZM5,5H10V6H5V5ZM5,12H6V13H5V12ZM6,7H8V8H7V9H6V7ZM6,11H7V12H6V11ZM7,10H8V11H7V10ZM8,9H9V10H8V9ZM8,11H11V12H8V11ZM9,8H10V9H9V8ZM10,7H11V8H10V7ZM11,6H12V7H11V6ZM11,10H13V11H11V10ZM12,5H13V6H12V5ZM13,4H14V5H13V4ZM13,7H14V8H13V7ZM13,9H14V10H13V9ZM14,8H15V9H14V8Z"/>
  </svg>
);
EyeHidden.displayName = 'EyeHidden';

export const Eye = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M1,8H2V9H1V8ZM2,7H3V8H2V7ZM2,9H3V10H2V9ZM3,6H5V7H3V6ZM3,10H5V11H3V10ZM5,5H11V6H5V5ZM5,11H11V12H5V11ZM6,7H8V8H7V9H6V7ZM7,9H9V10H7V9ZM9,7H10V9H9V7ZM11,6H13V7H11V6ZM11,10H13V11H11V10ZM13,7H14V8H13V7ZM13,9H14V10H13V9ZM14,8H15V9H14V8Z"/>
  </svg>
);
Eye.displayName = 'Eye';

export const FillBucket = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M7,1H9V2H10V3H11V4H12V5H13V6H12V7H11V8H10V9H9V10H8V11H7V10H6V9H5V8H4V7H3V6H4V5H5V4H6V3H7V1ZM8,3V4H7V5H6V6H5V7H6V8H7V9H8V8H9V7H10V6H11V5H10V4H9V3H8ZM12,8H13V9H14V10H13V12H12V10H11V9H12V8Z"/>
  </svg>
);
FillBucket.displayName = 'FillBucket';

export const FilmCamera = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M2,3H3V4H4V5H5V6H3V5H2V3ZM3,2H5V3H6V5H5V4H4V3H3V2ZM3,7H5V6H8V7H10V10H9V11H4V10H3V7ZM9,10V8H7V10H9ZM4,13H5V12H8V13H9V14H7V13H6V14H4V13ZM7,3H8V2H10V3H9V4H8V5H7V3ZM8,5H9V4H10V3H11V5H10V6H8V5ZM11,7H12V6H14V10H12V9H11V7Z"/>
  </svg>
);
FilmCamera.displayName = 'FilmCamera';

export const FilmStripOutline = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M4,1H5V2H4V1ZM4,3H5V4H4V3ZM4,5H5V6H4V5ZM4,7H5V8H4V7ZM4,9H5V10H4V9ZM4,11H5V12H4V11ZM4,13H5V14H4V13ZM6,1H7V2H6V1ZM6,5H7V10H6V5ZM6,13H7V14H6V13ZM7,2H10V3H7V2ZM7,4H10V5H7V4ZM7,10H10V11H7V10ZM7,12H10V13H7V12ZM10,1H11V2H10V1ZM10,5H11V10H10V5ZM10,13H11V14H10V13ZM12,1H13V2H12V1ZM12,3H13V4H12V3ZM12,5H13V6H12V5ZM12,7H13V8H12V7ZM12,9H13V10H12V9ZM12,11H13V12H12V11ZM12,13H13V14H12V13Z"/>
  </svg>
);
FilmStripOutline.displayName = 'FilmStripOutline';

export const FilmStrip = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M3,1H4V2H5V1H6V3H10V1H11V2H12V1H13V14H12V13H11V14H10V11H6V14H5V13H4V14H3V1ZM4,3V4H5V3H4ZM4,5V6H5V5H4ZM4,7V8H5V7H4ZM4,9V10H5V9H4ZM4,11V12H5V11H4ZM6,4V10H10V4H6ZM11,3V4H12V3H11ZM11,5V6H12V5H11ZM11,7V8H12V7H11ZM11,9V10H12V9H11ZM11,11V12H12V11H11Z"/>
  </svg>
);
FilmStrip.displayName = 'FilmStrip';

export const Fire = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M3,9H4V8H5V9H6V8H7V3H9V4H10V5H11V6H12V9H13V12H12V11H11V9H10V8H9V9H8V10H7V11H5V10H4V12H3V9ZM9,8V7H8V8H9ZM4,5H5V6H4V5ZM4,12H5V13H4V12ZM5,13H11V14H5V13ZM6,2H7V3H6V2ZM9,9H10V10H9V9ZM11,12H12V13H11V12Z"/>
  </svg>
);
Fire.displayName = 'Fire';

export const FolderClosed = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M2,3H8V4H13V5H3V6H2V3ZM2,7H3V6H14V13H2V7Z"/>
  </svg>
);
FolderClosed.displayName = 'FolderClosed';

export const FolderOpen = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M1,3H7V4H12V5H5V6H4V8H3V10H2V12H1V3ZM2,12H3V10H4V8H5V6H15V7H14V9H13V11H12V13H2V12Z"/>
  </svg>
);
FolderOpen.displayName = 'FolderOpen';

export const FullScreen = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M2,9H4V11H5V12H7V14H2V9ZM3,3H4V4H3V3ZM3,5H4V6H3V5ZM3,7H4V8H3V7ZM5,3H6V4H5V3ZM5,10H6V11H5V10ZM6,9H7V10H6V9ZM7,3H8V4H7V3ZM8,12H9V13H8V12ZM9,2H14V7H12V5H11V4H9V2ZM9,6H10V7H9V6ZM10,5H11V6H10V5ZM10,12H11V13H10V12ZM12,8H13V9H12V8ZM12,10H13V11H12V10ZM12,12H13V13H12V12Z"/>
  </svg>
);
FullScreen.displayName = 'FullScreen';

export const GameController = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M2,8H3V7H8V6H9V7H13V8H14V11H13V12H10V11H6V12H3V11H2V8ZM3,9V10H4V11H5V10H6V9H5V8H4V9H3ZM7,9V10H9V9H7ZM10,9V10H11V9H10ZM11,8V9H12V8H11ZM11,10V11H12V10H11ZM12,9V10H13V9H12ZM8,4H9V5H8V4ZM9,3H10V4H9V3ZM11,3H12V4H11V3ZM13,3H14V4H13V3Z"/>
  </svg>
);
GameController.displayName = 'GameController';

export const Globe = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M3,6H4V9H5V11H6V12H7V13H9V12H8V11H7V10H8V9H9V6H10V5H8V4H6V3H11V4H12V5H13V6H14V11H13V7H12V8H11V10H12V11H11V12H10V13H11V14H6V13H5V12H4V11H3V6ZM12,5H11V6H12V5ZM4,5H5V6H4V5ZM5,4H6V5H5V4ZM11,12H12V13H11V12ZM12,11H13V12H12V11Z"/>
  </svg>
);
Globe.displayName = 'Globe';

export const GoForward = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M3,6H4V5H5V4H9V2H10V3H11V4H12V5H13V6H12V7H11V8H10V9H9V6H6V7H5V11H6V12H9V11H10V10H11V12H10V13H9V14H5V13H4V12H3V6Z"/>
  </svg>
);
GoForward.displayName = 'GoForward';

export const Grid3X3 = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path d="M2,2H5V5H2V2ZM2,6H5V10H2V6ZM2,11H5V14H2V11ZM6,2H10V5H6V2ZM6,6H10V10H6V6ZM6,11H10V14H6V11ZM11,2H14V5H11V2ZM11,6H14V10H11V6ZM11,11H14V14H11V11Z"/>
  </svg>
);
Grid3X3.displayName = 'Grid3X3';

export const GripHorizontal = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path d="M3,5H5V7H3V5ZM7,5H9V7H7V5ZM11,5H13V7H11V5ZM3,9H5V11H3V9ZM7,9H9V11H7V9ZM11,9H13V11H11V9Z"/>
  </svg>
);
GripHorizontal.displayName = 'GripHorizontal';

export const GripVertical = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path d="M5,3H7V5H5V3ZM9,3H11V5H9V3ZM5,7H7V9H5V7ZM9,7H11V9H9V7ZM5,11H7V13H5V11ZM9,11H11V13H9V11Z"/>
  </svg>
);
GripVertical.displayName = 'GripVertical';

export const Hamburger = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M2,4H14V6H2V4ZM2,8H14V10H2V8ZM2,12H14V14H2V12Z"/>
  </svg>
);
Hamburger.displayName = 'Hamburger';

export const HandPoint = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M2,9H4V10H5V1H7V8H8V5H9V8H10V6H11V8H12V7H13V12H12V14H11V15H5V14H4V13H3V11H2V9Z"/>
  </svg>
);
HandPoint.displayName = 'HandPoint';

export const HardDrive = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M3,2H13V14H12V13H11V14H10V13H9V14H7V12H8V9H5V10H3V2ZM8,9H9V8H10V7H9V6H8V7H7V8H8V9ZM4,3V4H5V3H4ZM5,6V8H6V6H5ZM6,5V6H7V5H6ZM7,4V5H10V4H7ZM9,10V11H10V10H9ZM10,5V6H11V5H10ZM10,9V10H11V9H10ZM11,3V4H12V3H11ZM11,6V9H12V6H11ZM3,11H4V13H6V14H3V11ZM5,11H6V12H5V11ZM6,10H7V11H6V10ZM8,7H9V8H8V7Z"/>
  </svg>
);
HardDrive.displayName = 'HardDrive';

export const Headphones = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M2,10H3V6H4V9H5V13H3V12H2V10ZM4,5H5V6H4V5ZM5,4H6V3H10V4H11V5H5V4ZM11,5H12V6H11V5ZM11,9H12V6H13V10H14V12H13V13H11V9Z"/>
  </svg>
);
Headphones.displayName = 'Headphones';

export const Heart = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M1,6H2V4H3V3H4V2H6V1H10V2H12V3H13V4H14V6H15V10H14V12H13V13H12V14H10V15H6V14H4V13H3V12H2V10H1V6ZM3,8V10H4V11H5V12H7V11H8V10H9V9H10V8H11V7H12V5H10V6H9V7H8V8H7V9H5V8H3Z"/>
  </svg>
);
Heart.displayName = 'Heart';

export const Home = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M1,7H2V9H1V7ZM1,13H15V14H1V13ZM2,5H3V7H2V5ZM2,9H3V7H4V5H5V7H6V9H7V12H5V9H4V12H2V9ZM3,3H4V5H3V3ZM4,2H9V3H6V5H5V3H4V2ZM6,5H7V7H6V5ZM7,7H8V8H14V7H15V9H7V7ZM8,10H9V11H8V10ZM10,1H12V4H10V1ZM11,10H12V11H11V10ZM13,5H14V7H13V5ZM13,10H14V12H13V10Z"/>
  </svg>
);
Home.displayName = 'Home';

export const Home2 = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M1,9H2V10H1V9ZM2,8H3V9H2V8ZM3,3H5V5H4V6H3V3ZM3,7H4V8H3V7ZM3,9H4V8H5V7H6V6H7V5H9V6H10V7H11V8H12V9H13V14H9V10H7V14H3V9ZM4,11V13H6V11H4ZM10,11V13H12V11H10ZM4,6H5V7H4V6ZM5,5H6V6H5V5ZM6,4H7V5H6V4ZM7,3H9V4H7V3ZM9,4H10V5H9V4ZM10,5H11V6H10V5ZM11,6H12V7H11V6ZM12,7H13V8H12V7ZM13,8H14V9H13V8ZM14,9H15V10H14V9Z"/>
  </svg>
);
Home2.displayName = 'Home2';

export const Hourglass = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M4,2H12V3H4V2ZM4,14H12V15H4V14ZM5,4H6V5H7V6H6V7H5V4ZM5,10H6V13H5V10ZM6,7H7V8H6V7ZM6,9H7V10H6V9ZM7,6H8V7H7V6ZM7,8H8V7H9V6H8V5H10V4H11V7H10V8H9V9H7V8ZM9,9H10V10H9V9ZM10,10H11V13H10V10Z"/>
  </svg>
);
Hourglass.displayName = 'Hourglass';

export const InfoFilled = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M2,6H3V4H4V3H6V2H10V3H12V4H13V6H14V10H13V12H12V13H10V14H6V13H4V12H3V10H2V6ZM6,7V8H7V12H10V11H9V7H6ZM7,4V6H9V4H7Z"/>
  </svg>
);
InfoFilled.displayName = 'InfoFilled';

export const Info = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M6,3H7V2H9V3H10V4H9V5H7V4H6V3ZM6,7H9V13H10V14H7V8H6V7Z"/>
  </svg>
);
Info.displayName = 'Info';

export const Joystick = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M3,13H4V12H12V13H13V14H3V13ZM6,3H7V2H9V3H10V5H9V6H7V5H6V3ZM9,3H8V4H9V3ZM7,7H9V11H7V7Z"/>
  </svg>
);
Joystick.displayName = 'Joystick';

export const Lightbulb = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M4,4H5V3H6V2H10V3H9V4H10V5H11V4H12V8H11V9H10V11H6V9H5V8H4V4ZM6,12H10V13H6V12ZM6,14H10V15H6V14ZM10,3H11V4H10V3Z"/>
  </svg>
);
Lightbulb.displayName = 'Lightbulb';

export const Lightbulb2 = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M4,3H5V2H10V3H11V7H10V9H9V10H8V7H7V10H6V9H5V7H4V3ZM8,7H9V6H8V7ZM7,7V6H6V7H7ZM6,11H9V12H6V11ZM6,13H9V14H6V13Z"/>
  </svg>
);
Lightbulb2.displayName = 'Lightbulb2';

export const LineChart = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M2,2H3V3H4V4H3V13H12V12H13V13H14V14H2V2ZM4,9H5V11H4V9ZM5,8H6V9H5V8ZM6,7H7V8H6V7ZM7,8H8V9H7V8ZM8,9H9V10H8V9ZM9,8H10V9H9V8ZM10,6H11V8H10V6ZM11,5H12V6H11V5ZM12,4H13V5H12V4Z"/>
  </svg>
);
LineChart.displayName = 'LineChart';

export const List = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M2,2H5V5H2V2ZM2,6H5V9H2V6ZM3,7V8H4V7H3ZM2,10H5V13H2V10ZM3,11V12H4V11H3ZM6,4H14V5H6V4ZM6,8H14V9H6V8ZM6,12H14V13H6V12Z"/>
  </svg>
);
List.displayName = 'List';

export const LockClosed = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M3,8H13V13H12V14H4V13H3V8ZM7,10V12H8V13H9V10H7ZM5,3H6V2H10V3H11V7H10V4H9V3H7V4H6V7H5V3Z"/>
  </svg>
);
LockClosed.displayName = 'LockClosed';

export const LockOpen = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M3,8H13V13H12V14H4V13H3V8ZM7,10V12H9V11H10V10H7ZM5,2H6V1H10V2H11V4H10V3H9V2H7V3H6V7H5V2Z"/>
  </svg>
);
LockOpen.displayName = 'LockOpen';

export const MicrophoneMute = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M3,3H4V4H3V3ZM4,4H5V5H4V4ZM4,8H5V10H4V8ZM5,5H6V6H5V5ZM5,10H6V11H5V10ZM6,4H7V3H9V4H10V8H9V7H8V6H7V5H6V4ZM6,6H7V7H6V6ZM6,8H7V9H8V10H9V11H7V10H6V8ZM6,11H7V12H6V11ZM6,13H7V12H9V13H10V14H6V13ZM7,7H8V8H7V7ZM8,8H9V9H8V8ZM9,9H10V10H9V9ZM10,10H11V11H10V10ZM11,8H12V9H11V8ZM11,11H12V12H11V11ZM12,12H13V13H12V12Z"/>
  </svg>
);
MicrophoneMute.displayName = 'MicrophoneMute';

export const Microphone = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M4,8H5V10H4V8ZM5,10H6V11H5V10ZM6,4H7V5H6V4ZM6,6H7V7H6V6ZM6,8H7V7H9V8H10V10H9V11H7V10H6V8ZM6,11H7V12H6V11ZM6,13H7V12H9V13H10V14H6V13ZM7,3H9V4H7V3ZM7,5H9V6H7V5ZM9,4H10V5H9V4ZM9,6H10V7H9V6ZM9,11H10V12H9V11ZM10,10H11V11H10V10ZM11,8H12V10H11V8Z"/>
  </svg>
);
Microphone.displayName = 'Microphone';

export const Minus = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M3,7H13V9H3V7Z"/>
  </svg>
);
Minus.displayName = 'Minus';

export const Money = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M1,4H3V5H2V6H1V4ZM1,7H2V6H14V7H15V13H14V12H13V11H14V8H13V7H3V8H2V11H3V12H2V13H1V7ZM3,8H5V9H4V10H5V11H3V8ZM3,12H13V13H3V12ZM4,4H12V5H4V4ZM6,8H10V11H6V8ZM11,8H13V11H11V10H12V9H11V8ZM13,4H15V6H14V5H13V4Z"/>
  </svg>
);
Money.displayName = 'Money';

export const Moon = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fillRule="evenodd" clipRule="evenodd" d="M6 1H10V2H12V3H13V5H14V7H14V9H13V11H12V13H10V14H6V13H4V12H3V10H2V7H3V5H4V3H6V1ZM8 3H6V4H5V6H4V9H5V11H6V12H8V11H7V10H6V8H7V6H8V5H9V4H8V3Z" fill="currentColor"/>
  </svg>
);
Moon.displayName = 'Moon';

export const MoreHorizontal = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path d="M2,7H4V9H2V7ZM7,7H9V9H7V7ZM12,7H14V9H12V7Z"/>
  </svg>
);
MoreHorizontal.displayName = 'MoreHorizontal';

export const MoreVertical = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path d="M7,2H9V4H7V2ZM7,7H9V9H7V7ZM7,12H9V14H7V12Z"/>
  </svg>
);
MoreVertical.displayName = 'MoreVertical';

export const MultipleImages = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M3,3H11V11H3V3ZM4,8V10H10V9H9V8H8V7H7V6H6V7H5V8H4ZM8,5V6H9V5H8ZM5,12H12V5H13V13H5V12Z"/>
  </svg>
);
MultipleImages.displayName = 'MultipleImages';

export const Music8thNotes = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M2,11H3V10H5V3H13V12H12V13H9V11H10V10H12V5H6V12H5V13H2V11Z"/>
  </svg>
);
Music8thNotes.displayName = 'Music8thNotes';

export const OutlineBox = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M3,3H7V4H4V7H3V3ZM3,9H4V12H7V13H3V9ZM9,3H13V7H12V4H9V3ZM9,12H12V9H13V13H9V12Z"/>
  </svg>
);
OutlineBox.displayName = 'OutlineBox';

export const PaperPlane = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M2,7H4V6H6V5H8V4H10V3H12V4H11V5H9V6H8V7H7V8H5V9H3V8H2V7ZM3,10H4V11H3V10ZM5,11H6V12H7V13H6V14H5V11ZM6,10H7V9H8V8H9V7H10V6H11V5H12V4H13V6H12V8H11V10H10V13H8V12H7V11H6V10ZM12,2H14V4H13V3H12V2Z"/>
  </svg>
);
PaperPlane.displayName = 'PaperPlane';

export const Pause = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M4,4H7V13H4V4ZM9,4H12V13H9V4Z"/>
  </svg>
);
Pause.displayName = 'Pause';

export const Pencil = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M2,11H3V13H5V14H2V11ZM3,10H4V9H5V8H6V7H7V6H8V5H9V4H10V5H11V6H12V7H11V8H10V9H9V10H8V11H7V12H6V13H5V12H4V11H3V10ZM10,3H11V4H10V3ZM11,2H12V3H11V2ZM12,3H13V4H12V3ZM12,5H13V6H12V5ZM13,4H14V5H13V4Z"/>
  </svg>
);
Pencil.displayName = 'Pencil';

export const PictureInPicture = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M2,3H14V7H13V4H3V11H7V12H2V3ZM8,8H14V12H8V8ZM9,9V11H13V9H9Z"/>
  </svg>
);
PictureInPicture.displayName = 'PictureInPicture';

export const PieChart = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M2,6H3V5H4V4H5V3H8V5H7V9H13V11H12V12H11V13H10V14H5V13H4V12H3V11H2V6ZM8,6H9V3H10V2H11V3H12V4H13V5H14V8H8V6Z"/>
  </svg>
);
PieChart.displayName = 'PieChart';

export const Play = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M6,4H8V5H9V6H10V7H11V8H12V9H11V10H10V11H9V12H8V13H6V4Z"/>
  </svg>
);
Play.displayName = 'Play';

export const Plug = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M4,6H12V7H4V6ZM5,8H11V11H10V12H6V11H5V8ZM6,2H7V5H6V2ZM7,13H9V14H7V13ZM9,2H10V5H9V2Z"/>
  </svg>
);
Plug.displayName = 'Plug';

export const Plus = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M3,7H7V3H9V7H13V9H9V13H7V9H3V7Z"/>
  </svg>
);
Plus.displayName = 'Plus';

export const Power1 = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M2,7H3V5H4V4H6V5H5V6H4V11H5V12H7V13H9V12H11V11H12V6H11V5H10V4H12V5H13V7H14V10H13V12H12V13H10V14H6V13H4V12H3V10H2V7ZM7,2H9V7H7V2Z"/>
  </svg>
);
Power1.displayName = 'Power1';

export const Power2 = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M2,5H3V4H4V3H6V5H5V6H4V10H5V11H6V12H10V11H11V10H12V6H11V5H10V3H12V4H13V5H14V11H13V12H12V13H11V14H5V13H4V12H3V11H2V5ZM7,1H9V7H7V1Z"/>
  </svg>
);
Power2.displayName = 'Power2';

export const Print = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M1,7H2V6H14V7H15V11H12V10H4V11H1V7ZM10,7V8H11V7H10ZM12,7V8H13V7H12ZM1,12H4V13H1V12ZM5,1H8V4H11V5H5V1ZM5,11H6V12H10V11H11V15H5V11ZM6,13V14H10V13H6ZM9,1H10V2H11V3H9V1ZM12,12H15V13H12V12Z"/>
  </svg>
);
Print.displayName = 'Print';

export const QuestionFilled = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M2,3H3V2H13V3H14V13H13V14H3V13H2V3ZM5,4V6H7V5H9V7H8V8H7V10H9V9H10V8H11V4H10V3H6V4H5ZM7,11V13H9V11H7Z"/>
  </svg>
);
QuestionFilled.displayName = 'QuestionFilled';

export const Question = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M4,4H5V3H6V2H11V3H12V4H13V7H12V8H10V9H9V10H7V8H8V7H10V6H11V5H10V4H7V5H6V6H4V4ZM7,12H9V14H7V12Z"/>
  </svg>
);
Question.displayName = 'Question';

export const Queue = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M1,3H10V5H1V3ZM1,6H10V8H1V6ZM1,9H10V11H1V9ZM12,4H13V5H14V6H15V7H14V8H13V9H12V4Z"/>
  </svg>
);
Queue.displayName = 'Queue';

export const RadMark = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 65 65" fill="currentColor" className={className} {...props}>
    <path fillRule="evenodd" clipRule="evenodd" d="M29.6393 4.93988V0H34.5791V4.93988H39.519V9.87976H24.6994V4.93988H29.6393ZM59.2789 29.6392H64.2188V34.5791H59.2789V39.5189H54.339V24.6993H59.2789V29.6392ZM0 34.5797H4.93988V39.5196H9.87976V24.7H4.93988V29.6399H0V34.5797ZM14.8198 14.8189V19.7587H9.87988V9.87899H19.7596V14.8189H14.8198ZM44.4591 14.8189H49.399V19.7587H54.3389V9.87899H44.4591V14.8189ZM49.399 49.3981L49.399 44.4582H54.3389V54.338H44.4591V49.3981H49.399ZM19.7596 49.3981H14.8198V44.4582H9.87988V54.338H19.7596V49.3981ZM34.5797 59.279V64.2188H29.6398L29.6398 59.279H24.6999V54.3391H39.5195V59.279H34.5797ZM24.6991 14.8204H39.5187V19.7603H44.4586V24.7002H49.3985V39.5198H44.4586V44.4597H39.5187V49.3996H24.6991V44.4597H19.7592V39.5198H14.8193V24.7002H19.7592V19.7603H24.6991V14.8204Z"/>
  </svg>
);
RadMark.displayName = 'RadMark';

export const RadiantsLogo = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 65 65" fill="currentColor" className={className} {...props}>
    <path fillRule="evenodd" clipRule="evenodd" d="M29.6393 4.93988V0H34.5791V4.93988H39.519V9.87976H24.6994V4.93988H29.6393ZM59.2789 29.6392H64.2188V34.5791H59.2789V39.5189H54.339V24.6993H59.2789V29.6392ZM0 34.5797H4.93988V39.5196H9.87976V24.7H4.93988V29.6399H0V34.5797ZM14.8198 14.8189V19.7587H9.87988V9.87899H19.7596V14.8189H14.8198ZM44.4591 14.8189H49.399V19.7587H54.3389V9.87899H44.4591V14.8189ZM49.399 49.3981L49.399 44.4582H54.3389V54.338H44.4591V49.3981H49.399ZM19.7596 49.3981H14.8198V44.4582H9.87988V54.338H19.7596V49.3981ZM34.5797 59.279V64.2188H29.6398L29.6398 59.279H24.6999V54.3391H39.5195V59.279H34.5797ZM24.6991 14.8204H39.5187V19.7603H44.4586V24.7002H49.3985V39.5198H44.4586V44.4597H39.5187V49.3996H24.6991V44.4597H19.7592V39.5198H14.8193V24.7002H19.7592V19.7603H24.6991V14.8204Z" fill="currentColor"/>
  </svg>
);
RadiantsLogo.displayName = 'RadiantsLogo';

export const RecordPlayback = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M4,7H5V6H6V5H9V6H10V7H11V10H10V11H9V12H6V11H5V10H4V7Z"/>
  </svg>
);
RecordPlayback.displayName = 'RecordPlayback';

export const RecordPlayer = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M3,4H4V3H10V2H11V3H12V9H11V10H4V9H3V4ZM5,5V8H6V9H9V8H10V5H9V4H6V5H5ZM10,4V5H11V4H10ZM3,10H4V11H11V10H12V12H11V14H4V12H3V10ZM5,12V13H10V12H5ZM7,6H8V7H7V6Z"/>
  </svg>
);
RecordPlayer.displayName = 'RecordPlayer';

export const RefreshFilled = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M2,3H3V2H13V3H14V13H13V14H3V13H2V3ZM3,6V9H4V6H3ZM4,5V6H7V8H8V7H9V6H10V5H9V4H8V3H7V5H4ZM4,9V10H5V9H4ZM6,10V11H7V12H8V13H9V11H12V10H9V8H8V9H7V10H6ZM11,6V7H12V6H11ZM12,7V10H13V7H12Z"/>
  </svg>
);
RefreshFilled.displayName = 'RefreshFilled';

export const Refresh1 = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M2,8H3V7H4V6H5V7H6V8H7V9H6V10H7V11H12V12H11V13H6V12H5V11H4V9H2V8ZM4,4H5V3H10V4H11V5H12V7H14V8H13V9H12V10H11V9H10V8H9V7H10V6H9V5H4V4Z"/>
  </svg>
);
Refresh1.displayName = 'Refresh1';

export const Reload = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M3,5H4V4H5V3H6V2H7V4H11V5H12V6H13V12H12V13H11V14H7V13H6V12H5V10H6V11H7V12H10V11H11V7H10V6H7V9H6V8H5V7H4V6H3V5Z"/>
  </svg>
);
Reload.displayName = 'Reload';

export const ResizeCorner = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M14,2H16V4H14V2ZM10,6H12V8H10V6ZM14,6H16V8H14V6ZM6,10H8V12H6V10ZM10,10H12V12H10V10ZM14,10H16V12H14V10ZM2,14H4V16H2V14ZM6,14H8V16H6V14ZM10,14H12V16H10V14ZM14,14H16V16H14V14Z"/>
  </svg>
);
ResizeCorner.displayName = 'ResizeCorner';

export const Save2 = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M2,8H3V12H4V13H12V12H13V5H12V4H9V3H13V4H14V13H13V14H3V13H2V8ZM3,3H6V4H7V5H8V6H9V8H11V9H10V10H9V11H7V10H6V9H5V8H7V6H6V5H5V4H3V3Z"/>
  </svg>
);
Save2.displayName = 'Save2';

export const Save = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M2,3H3V2H4V7H11V2H12V3H13V4H14V14H12V8H4V14H2V3ZM5,2H7V5H9V2H10V6H5V2ZM5,9H11V14H5V9ZM6,10V11H10V10H6ZM6,12V13H10V12H6Z"/>
  </svg>
);
Save.displayName = 'Save';

export const Search = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M2,4H3V8H2V4ZM3,3H4V4H3V3ZM3,8H4V9H3V8ZM4,2H8V3H4V2ZM4,5H5V4H7V5H8V7H7V8H5V7H4V5ZM5,7H6V6H5V7ZM4,9H8V10H4V9ZM8,3H9V4H8V3ZM8,8H9V9H8V8ZM9,4H10V8H9V4ZM9,10H10V9H11V10H12V11H13V12H14V14H12V13H11V12H10V11H9V10Z"/>
  </svg>
);
Search.displayName = 'Search';

export const SeekBack = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M2,8H3V7H4V6H5V5H6V4H8V7H7V8H6V9H7V10H8V13H6V12H5V11H4V10H3V9H2V8ZM8,8H9V7H10V6H11V5H12V4H14V13H12V12H11V11H10V10H9V9H8V8Z"/>
  </svg>
);
SeekBack.displayName = 'SeekBack';

export const SeekForward = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M2,4H4V5H5V6H6V7H7V8H8V9H7V10H6V11H5V12H4V13H2V4ZM8,4H10V5H11V6H12V7H13V8H14V9H13V10H12V11H11V12H10V13H8V10H9V9H10V8H9V7H8V4Z"/>
  </svg>
);
SeekForward.displayName = 'SeekForward';

export const SettingsCog = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M2,7H4V5H3V3H5V4H7V2H9V4H11V3H13V5H12V7H14V9H12V11H13V13H11V12H9V14H7V12H5V13H3V11H4V9H2V7ZM6,7V9H7V10H9V9H10V7H9V6H7V7H6Z"/>
  </svg>
);
SettingsCog.displayName = 'SettingsCog';

export const Share = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M2,5H3V4H7V5H4V6H3V13H4V14H12V13H13V10H14V14H13V15H3V14H2V5ZM6,8H7V7H8V6H9V5H11V3H12V4H13V5H14V7H13V8H12V9H11V7H9V8H8V9H7V11H6V8Z"/>
  </svg>
);
Share.displayName = 'Share';

export const SkipBack = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M4,4H6V8H5V9H6V13H4V4ZM6,8H7V7H8V6H9V5H10V4H12V13H10V12H9V11H8V10H7V9H6V8Z"/>
  </svg>
);
SkipBack.displayName = 'SkipBack';

export const SkipForward = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M4,4H6V5H7V6H8V7H9V8H10V9H9V10H8V11H7V12H6V13H4V4ZM10,4H12V13H10V9H11V8H10V4Z"/>
  </svg>
);
SkipForward.displayName = 'SkipForward';

export const SkullAndCrossbones = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M1,3H2V2H4V4H5V5H4V6H3V5H1V3ZM1,12H3V11H4V12H5V13H4V15H2V14H1V12ZM3,7H4V6H5V5H11V6H12V7H13V10H12V11H10V13H6V11H4V10H3V7ZM4,7V9H7V7H4ZM12,7H9V9H12V7ZM7,10V11H9V10H7ZM11,4H12V2H14V3H15V5H13V6H12V5H11V4ZM11,12H12V11H13V12H15V14H14V15H12V13H11V12Z"/>
  </svg>
);
SkullAndCrossbones.displayName = 'SkullAndCrossbones';

export const SortDescending = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M2,10H3V11H2V10ZM3,11H4V3H5V11H6V12H5V13H4V12H3V11ZM6,10H7V11H6V10ZM8,5H10V6H8V5ZM8,7H11V8H8V7ZM8,9H12V10H8V9ZM8,11H13V12H8V11Z"/>
  </svg>
);
SortDescending.displayName = 'SortDescending';

export const SortFilterEmpty = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M2,2H4V3H5V4H3V5H2V2ZM3,5H4V6H3V5ZM4,1H12V2H4V1ZM4,6H5V7H4V6ZM5,4H11V5H5V4ZM5,7H6V8H5V7ZM6,8H7V9H6V8ZM7,9H8V12H9V13H8V14H7V9ZM9,11H10V12H9V11ZM10,7H11V11H10V7ZM11,3H12V2H14V5H13V4H11V3ZM11,6H12V7H11V6ZM12,5H13V6H12V5Z"/>
  </svg>
);
SortFilterEmpty.displayName = 'SortFilterEmpty';

export const SortFilterFilled = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M3,3H4V4H5V5H11V4H12V3H13V7H12V8H11V9H10V12H9V13H8V14H7V10H6V9H5V8H4V7H3V3ZM4,2H12V3H4V2Z"/>
  </svg>
);
SortFilterFilled.displayName = 'SortFilterFilled';

export const Sparkles = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path d="M4,7H5V5H6V3H7V2H12V4H11V5H10V6H9V7H12V9H11V10H10V11H9V12H8V13H7V14H6V12H7V10H8V9H4V7Z"/>
  </svg>
);
Sparkles.displayName = 'Sparkles';

export const StopPlayback = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M4,4H13V13H4V4Z"/>
  </svg>
);
StopPlayback.displayName = 'StopPlayback';

export const Swap = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M1,1H8V6H1V1ZM2,2V5H7V2H2ZM3,8H4V7H5V8H6V9H5V11H7V12H4V9H3V8ZM8,10H15V15H8V10ZM9,11V14H14V11H9ZM9,3H12V7H13V8H12V9H11V8H10V7H11V4H9V3Z"/>
  </svg>
);
Swap.displayName = 'Swap';

export const Tape = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M1,5H2V4H14V5H15V12H14V13H12V12H11V11H5V12H4V13H2V12H1V5ZM14,12V11H13V12H14ZM2,12H3V11H2V12ZM2,6V9H3V10H6V9H7V10H9V9H10V10H13V9H14V6H13V5H10V6H9V5H7V6H6V5H3V6H2ZM3,7H4V8H3V7ZM4,6H5V7H4V6ZM4,8H5V9H4V8ZM5,7H6V8H5V7ZM5,12H11V13H5V12ZM7,7H9V8H7V7ZM10,7H11V8H10V7ZM11,6H12V7H11V6ZM11,8H12V9H11V8ZM12,7H13V8H12V7Z"/>
  </svg>
);
Tape.displayName = 'Tape';

export const Telephone = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M1,6H2V4H4V3H11V4H13V6H14V8H10V6H11V5H4V6H5V8H1V6ZM2,11H3V10H4V9H5V8H6V7H9V8H10V9H11V10H12V11H13V13H12V14H3V13H2V11ZM5,9V10H6V9H5ZM10,9H9V10H10V9ZM5,11V12H6V11H5ZM7,8V9H8V8H7ZM7,10V11H8V10H7ZM7,12V13H8V12H7ZM9,11V12H10V11H9Z"/>
  </svg>
);
Telephone.displayName = 'Telephone';

export const TrashFull = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M2,3H4V4H5V3H6V4H7V5H3V4H2V3ZM3,6H12V13H11V14H4V13H3V6ZM4,7V12H5V7H4ZM6,7V12H7V7H6ZM8,7V12H9V7H8ZM10,7V12H11V7H10ZM4,2H5V3H4V2ZM6,2H8V4H7V3H6V2ZM8,4H9V3H10V2H11V5H8V4ZM12,3H14V4H13V5H12V3Z"/>
  </svg>
);
TrashFull.displayName = 'TrashFull';

export const TrashOpen = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M3,2H5V3H3V2ZM3,4H4V5H3V4ZM3,6H8V12H9V7H10V12H11V8H12V13H11V14H4V13H3V6ZM4,7V12H5V7H4ZM6,7V12H7V7H6ZM5,3H8V4H9V5H7V4H5V3ZM8,2H10V3H8V2ZM9,5H11V4H12V6H13V7H11V6H9V5ZM10,3H11V4H10V3ZM13,7H14V8H13V7Z"/>
  </svg>
);
TrashOpen.displayName = 'TrashOpen';

export const Trash = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M2,4H5V3H6V4H9V3H10V4H13V5H2V4ZM3,6H12V13H11V14H4V13H3V6ZM4,7V12H5V7H4ZM6,7V12H7V7H6ZM8,7V12H9V7H8ZM10,7V12H11V7H10ZM6,2H9V3H6V2Z"/>
  </svg>
);
Trash.displayName = 'Trash';

export const Trophy = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M2,3H4V4H3V6H2V3ZM3,6H4V7H3V6ZM5,2H11V8H10V9H9V12H10V13H11V14H5V13H6V12H7V9H6V8H5V2ZM12,3H14V6H13V4H12V3ZM12,6H13V7H12V6Z"/>
  </svg>
);
Trophy.displayName = 'Trophy';

export const Trophy2 = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M1,4H4V3H12V4H15V8H14V5H13V7H12V8H11V9H10V10H9V13H11V14H12V15H4V14H5V13H7V10H6V9H5V8H4V7H3V5H2V8H1V4ZM2,8H3V9H2V8ZM3,1H13V2H3V1ZM3,9H5V10H3V9ZM11,9H13V10H11V9ZM13,8H14V9H13V8Z"/>
  </svg>
);
Trophy2.displayName = 'Trophy2';

export const Tv = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M1,6H6V5H7V4H9V5H10V6H15V9H14V7H11V9H10V7H2V14H10V10H11V14H14V10H15V15H1V6ZM3,10H4V11H3V10ZM4,1H5V2H4V1ZM4,9H5V10H4V9ZM5,2H6V3H5V2ZM5,8H6V9H5V8ZM5,12H6V13H5V12ZM6,3H7V4H6V3ZM6,11H7V12H6V11ZM7,10H8V11H7V10ZM8,9H9V10H8V9ZM9,3H10V4H9V3ZM10,2H11V3H10V2ZM11,9H12V8H13V9H14V10H13V11H12V10H11V9ZM12,12H13V13H12V12Z"/>
  </svg>
);
Tv.displayName = 'Tv';

export const Twitter = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="-2 -3 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" fillRule="evenodd" clipRule="evenodd" d="M8 0H7V1H6V2V3H5H4H3V2H2V1H1V0H0V1V2V3H1V4H0V5H1H2V6H1V7H2H3V8H2V9H1V8H0V9H1V10H2H3H4H5H6V9H7H8V8H9V7H10V6V5H11V4V3V2H12V1V0H11V1H10V0H9H8Z"/>
  </svg>
);
Twitter.displayName = 'Twitter';

export const Underline = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M2,13H3V12H14V13H13V14H2V13Z"/>
  </svg>
);
Underline.displayName = 'Underline';

export const Upload = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M2,9H3V12H4V13H12V12H13V9H14V13H13V14H3V13H2V9ZM5,4H6V3H7V2H9V3H10V4H11V5H9V11H7V5H5V4Z"/>
  </svg>
);
Upload.displayName = 'Upload';

export const UsbIcon = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M5,6H6V8H5V6ZM6,8H7V9H6V8ZM7,2H8V1H9V2H10V3H9V7H10V8H9V12H8V10H7V9H8V3H7V2ZM7,12H8V13H7V12ZM8,13H9V14H8V13ZM9,12H10V13H9V12ZM10,6H11V7H10V6ZM11,4H12V6H11V4Z"/>
  </svg>
);
UsbIcon.displayName = 'UsbIcon';

export const Usb = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M4,8H5V7H11V8H12V13H11V14H5V13H4V8ZM5,3H11V6H5V3ZM6,4V5H7V4H6ZM9,4V5H10V4H9Z"/>
  </svg>
);
Usb.displayName = 'Usb';

export const Usericon = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M2,3H3V2H13V3H14V13H13V14H9V12H7V11H6V14H3V13H2V3ZM7,11H11V9H12V4H11V3H6V4H5V8H6V10H7V11ZM8,6H9V7H8V6ZM10,6H11V7H10V6Z"/>
  </svg>
);
Usericon.displayName = 'Usericon';

export const VolumeFaders = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M2,6H5V7H2V6ZM3,3H4V5H3V3ZM3,8H4V13H3V8ZM5,9H8V10H5V9ZM6,3H7V8H6V3ZM6,11H7V13H6V11ZM8,7H11V8H8V7ZM9,3H10V6H9V3ZM9,9H10V13H9V9ZM11,5H14V6H11V5ZM12,3H13V4H12V3ZM12,7H13V13H12V7Z"/>
  </svg>
);
VolumeFaders.displayName = 'VolumeFaders';

export const VolumeHigh = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M2,6H4V10H2V6ZM5,5H6V4H7V3H8V13H7V12H6V11H5V5ZM9,6H10V7H9V6ZM9,9H10V10H9V9ZM10,3H11V4H10V3ZM10,7H11V9H10V7ZM10,12H11V13H10V12ZM11,4H12V5H11V4ZM11,11H12V12H11V11ZM12,5H13V11H12V5Z"/>
  </svg>
);
VolumeHigh.displayName = 'VolumeHigh';

export const VolumeMute = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M2,6H4V10H2V6ZM5,5H6V4H7V3H8V13H7V12H6V11H5V5ZM9,5H10V6H9V5ZM9,9H10V10H9V9ZM10,6H11V7H10V6ZM10,8H11V9H10V8ZM11,7H12V8H11V7ZM12,6H13V7H12V6ZM12,8H13V9H12V8ZM13,5H14V6H13V5ZM13,9H14V10H13V9Z"/>
  </svg>
);
VolumeMute.displayName = 'VolumeMute';

export const WarningFilledOutline = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M1,11H2V13H1V11ZM2,9H3V11H2V9ZM2,13H14V14H2V13ZM3,7H4V9H3V7ZM3,11H4V9H5V7H6V5H7V3H9V5H10V7H11V9H12V11H13V12H3V11ZM7,6V8H8V9H9V6H7ZM8,10V11H9V10H8ZM4,5H5V7H4V5ZM5,3H6V5H5V3ZM6,2H7V3H6V2ZM7,1H9V2H7V1ZM9,2H10V3H9V2ZM10,3H11V5H10V3ZM11,5H12V7H11V5ZM12,7H13V9H12V7ZM13,9H14V11H13V9ZM14,11H15V13H14V11Z"/>
  </svg>
);
WarningFilledOutline.displayName = 'WarningFilledOutline';

export const WarningFilled = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M2,11H3V9H4V7H5V5H6V8H7V10H9V8H10V5H11V7H12V9H13V11H14V13H13V14H3V13H2V11ZM7,11V13H9V11H7ZM6,3H7V2H9V3H10V5H9V4H7V5H6V3Z"/>
  </svg>
);
WarningFilled.displayName = 'WarningFilled';

export const WarningHollow = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M2,11H3V13H2V11ZM3,9H4V11H3V9ZM3,13H13V14H3V13ZM4,7H5V9H4V7ZM5,5H6V7H5V5ZM6,3H7V5H6V3ZM7,2H9V3H7V2ZM7,6H9V10H8V9H7V6ZM8,11H9V12H8V11ZM9,3H10V5H9V3ZM10,5H11V7H10V5ZM11,7H12V9H11V7ZM12,9H13V11H12V9ZM13,11H14V13H13V11Z"/>
  </svg>
);
WarningHollow.displayName = 'WarningHollow';

export const Wifi = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M1,7H2V8H1V7ZM2,6H3V7H2V6ZM3,5H4V6H3V5ZM3,8H4V9H3V8ZM4,4H12V5H4V4ZM4,7H5V8H4V7ZM5,6H11V7H5V6ZM5,9H6V10H5V9ZM6,8H10V9H6V8ZM6,11H7V10H9V11H10V12H9V13H7V12H6V11ZM10,9H11V10H10V9ZM11,7H12V8H11V7ZM12,5H13V6H12V5ZM12,8H13V9H12V8ZM13,6H14V7H13V6ZM14,7H15V8H14V7Z"/>
  </svg>
);
Wifi.displayName = 'Wifi';

export const WindowError = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M2,4H14V7H13V5H3V11H7V12H2V4ZM4,6H10V7H9V8H8V9H7V10H4V6ZM8,9H9V8H10V7H13V8H14V9H15V12H14V13H13V14H10V13H9V12H8V9ZM10,9V10H11V9H10ZM10,11V12H11V11H10ZM11,10V11H12V10H11ZM12,9V10H13V9H12ZM12,11V12H13V11H12Z"/>
  </svg>
);
WindowError.displayName = 'WindowError';

export const Windows = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M2,7H5V3H14V10H11V14H2V7ZM3,9V13H10V9H3ZM6,5V7H11V9H13V5H6Z"/>
  </svg>
);
Windows.displayName = 'Windows';

export const Wrench = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M2,12H3V13H4V14H2V12ZM3,11H4V10H5V9H6V8H7V7H8V3H9V2H11V3H10V4H9V5H10V6H11V7H12V6H13V5H14V7H13V8H9V9H8V10H7V11H6V12H5V13H4V12H3V11Z"/>
  </svg>
);
Wrench.displayName = 'Wrench';

export const ZipFile = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M3,2H10V3H9V6H12V5H13V14H3V2ZM4,3V13H7V12H8V11H7V10H8V9H7V8H8V7H7V6H8V3H4ZM8,8V9H9V10H8V11H9V12H8V13H12V7H9V8H8ZM10,3H11V4H10V3ZM11,4H12V5H11V4Z"/>
  </svg>
);
ZipFile.displayName = 'ZipFile';

export const ZipFile2 = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" className={className} {...props}>
    <path fill="currentColor" d="M3,2H10V3H9V6H12V5H13V7H8V3H4V13H13V14H3V2ZM6,8H9V10H8V9H6V8ZM6,11H7V10H8V11H9V12H6V11ZM10,3H11V4H10V3ZM10,8H11V12H10V8ZM11,4H12V5H11V4ZM12,8H14V9H13V10H14V11H13V12H12V8ZM14,9H15V10H14V9Z"/>
  </svg>
);
ZipFile2.displayName = 'ZipFile2';

/** All generated icon names (kebab-case, matching SVG filenames) */
export const GENERATED_ICON_NAMES = [
  "USDC",
  "broadcast-dish",
  "broken-battery",
  "calendar",
  "calendar2",
  "camera",
  "cd-horizontal",
  "cd",
  "cell-bars",
  "checkmark",
  "chevron-down",
  "chevron-left",
  "chevron-right",
  "clock",
  "close-filled",
  "close",
  "code-file",
  "code-folder",
  "code-window-filled",
  "code-window",
  "coins",
  "comments-blank",
  "comments-typing",
  "computer",
  "copied-to-clipboard",
  "copy-to-clipboard",
  "copy",
  "crosshair-3",
  "crosshair1",
  "crosshair2-retro",
  "crosshair2",
  "crosshair4",
  "cursor-text",
  "cursor2",
  "cursors1",
  "cut",
  "discord",
  "document-image",
  "document",
  "document2",
  "download",
  "eject",
  "electric",
  "envelope-closed",
  "envelope-open",
  "equalizer",
  "eye-hidden",
  "eye",
  "fill-bucket",
  "film-camera",
  "film-strip-outline",
  "film-strip",
  "fire",
  "folder-closed",
  "folder-open",
  "full-screen",
  "game-controller",
  "globe",
  "go-forward",
  "grid-3x3",
  "grip-horizontal",
  "grip-vertical",
  "hamburger",
  "hand-point",
  "hard-drive",
  "headphones",
  "heart",
  "home",
  "home2",
  "hourglass",
  "info-filled",
  "info",
  "joystick",
  "lightbulb",
  "lightbulb2",
  "line-chart",
  "list",
  "lock-closed",
  "lock-open",
  "microphone-mute",
  "microphone",
  "minus",
  "money",
  "moon",
  "more-horizontal",
  "more-vertical",
  "multiple-images",
  "music-8th-notes",
  "outline-box",
  "paper-plane",
  "pause",
  "pencil",
  "picture-in-picture",
  "pie-chart",
  "play",
  "plug",
  "plus",
  "power1",
  "power2",
  "print",
  "question-filled",
  "question",
  "queue",
  "rad-mark",
  "radiants-logo",
  "record-playback",
  "record-player",
  "refresh-filled",
  "refresh1",
  "reload",
  "resize-corner",
  "save-2",
  "save",
  "search",
  "seek-back",
  "seek-forward",
  "settings-cog",
  "share",
  "skip-back",
  "skip-forward",
  "skull-and-crossbones",
  "sort-descending",
  "sort-filter-empty",
  "sort-filter-filled",
  "sparkles",
  "stop-playback",
  "swap",
  "tape",
  "telephone",
  "trash-full",
  "trash-open",
  "trash",
  "trophy",
  "trophy2",
  "tv",
  "twitter",
  "underline",
  "upload",
  "usb-icon",
  "usb",
  "usericon",
  "volume-faders",
  "volume-high",
  "volume-mute",
  "warning-filled-outline",
  "warning-filled",
  "warning-hollow",
  "wifi",
  "window-error",
  "windows",
  "wrench",
  "zip-file",
  "zip-file2"
] as const;

export type GeneratedIconName = (typeof GENERATED_ICON_NAMES)[number];

/** Lookup map: kebab-case name → inline icon component */
export const ICON_BY_NAME: Record<string, (props: IconProps) => ReactElement> = {
  'USDC': USDC,
  'broadcast-dish': BroadcastDish,
  'broken-battery': BrokenBattery,
  'calendar': Calendar,
  'calendar2': Calendar2,
  'camera': Camera,
  'cd-horizontal': CdHorizontal,
  'cd': Cd,
  'cell-bars': CellBars,
  'checkmark': Checkmark,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'clock': Clock,
  'close-filled': CloseFilled,
  'close': Close,
  'code-file': CodeFile,
  'code-folder': CodeFolder,
  'code-window-filled': CodeWindowFilled,
  'code-window': CodeWindow,
  'coins': Coins,
  'comments-blank': CommentsBlank,
  'comments-typing': CommentsTyping,
  'computer': Computer,
  'copied-to-clipboard': CopiedToClipboard,
  'copy-to-clipboard': CopyToClipboard,
  'copy': Copy,
  'crosshair-3': Crosshair3,
  'crosshair1': Crosshair1,
  'crosshair2-retro': Crosshair2Retro,
  'crosshair2': Crosshair2,
  'crosshair4': Crosshair4,
  'cursor-text': CursorText,
  'cursor2': Cursor2,
  'cursors1': Cursors1,
  'cut': Cut,
  'discord': Discord,
  'document-image': DocumentImage,
  'document': Document,
  'document2': Document2,
  'download': Download,
  'eject': Eject,
  'electric': Electric,
  'envelope-closed': EnvelopeClosed,
  'envelope-open': EnvelopeOpen,
  'equalizer': Equalizer,
  'eye-hidden': EyeHidden,
  'eye': Eye,
  'fill-bucket': FillBucket,
  'film-camera': FilmCamera,
  'film-strip-outline': FilmStripOutline,
  'film-strip': FilmStrip,
  'fire': Fire,
  'folder-closed': FolderClosed,
  'folder-open': FolderOpen,
  'full-screen': FullScreen,
  'game-controller': GameController,
  'globe': Globe,
  'go-forward': GoForward,
  'grid-3x3': Grid3X3,
  'grip-horizontal': GripHorizontal,
  'grip-vertical': GripVertical,
  'hamburger': Hamburger,
  'hand-point': HandPoint,
  'hard-drive': HardDrive,
  'headphones': Headphones,
  'heart': Heart,
  'home': Home,
  'home2': Home2,
  'hourglass': Hourglass,
  'info-filled': InfoFilled,
  'info': Info,
  'joystick': Joystick,
  'lightbulb': Lightbulb,
  'lightbulb2': Lightbulb2,
  'line-chart': LineChart,
  'list': List,
  'lock-closed': LockClosed,
  'lock-open': LockOpen,
  'microphone-mute': MicrophoneMute,
  'microphone': Microphone,
  'minus': Minus,
  'money': Money,
  'moon': Moon,
  'more-horizontal': MoreHorizontal,
  'more-vertical': MoreVertical,
  'multiple-images': MultipleImages,
  'music-8th-notes': Music8thNotes,
  'outline-box': OutlineBox,
  'paper-plane': PaperPlane,
  'pause': Pause,
  'pencil': Pencil,
  'picture-in-picture': PictureInPicture,
  'pie-chart': PieChart,
  'play': Play,
  'plug': Plug,
  'plus': Plus,
  'power1': Power1,
  'power2': Power2,
  'print': Print,
  'question-filled': QuestionFilled,
  'question': Question,
  'queue': Queue,
  'rad-mark': RadMark,
  'radiants-logo': RadiantsLogo,
  'record-playback': RecordPlayback,
  'record-player': RecordPlayer,
  'refresh-filled': RefreshFilled,
  'refresh1': Refresh1,
  'reload': Reload,
  'resize-corner': ResizeCorner,
  'save-2': Save2,
  'save': Save,
  'search': Search,
  'seek-back': SeekBack,
  'seek-forward': SeekForward,
  'settings-cog': SettingsCog,
  'share': Share,
  'skip-back': SkipBack,
  'skip-forward': SkipForward,
  'skull-and-crossbones': SkullAndCrossbones,
  'sort-descending': SortDescending,
  'sort-filter-empty': SortFilterEmpty,
  'sort-filter-filled': SortFilterFilled,
  'sparkles': Sparkles,
  'stop-playback': StopPlayback,
  'swap': Swap,
  'tape': Tape,
  'telephone': Telephone,
  'trash-full': TrashFull,
  'trash-open': TrashOpen,
  'trash': Trash,
  'trophy': Trophy,
  'trophy2': Trophy2,
  'tv': Tv,
  'twitter': Twitter,
  'underline': Underline,
  'upload': Upload,
  'usb-icon': UsbIcon,
  'usb': Usb,
  'usericon': Usericon,
  'volume-faders': VolumeFaders,
  'volume-high': VolumeHigh,
  'volume-mute': VolumeMute,
  'warning-filled-outline': WarningFilledOutline,
  'warning-filled': WarningFilled,
  'warning-hollow': WarningHollow,
  'wifi': Wifi,
  'window-error': WindowError,
  'windows': Windows,
  'wrench': Wrench,
  'zip-file': ZipFile,
  'zip-file2': ZipFile2,
};
