/**
 * AUTO-GENERATED - DO NOT EDIT
 *
 * Generated by: scripts/generate-icons.ts
 * Source:       runtime alias map (42 icons)
 */

export { ICON_ALIASES } from './manifest';
export type { IconAliasName } from './manifest';
