/**
 * AUTO-GENERATED — DO NOT EDIT
 *
 * Generated by: scripts/generate-icons.ts
 * Source:       runtime alias map (46 icons)
 *
 * To regenerate: pnpm generate:icons
 */

export const ICON_ALIASES = {
  check: 'checkmark',
  'checkmark-filled': 'checkmark',
  'chevron-left': 'chevron-left',
  'chevron-right': 'chevron-right',
  close: 'close',
  collapse: 'minus',
  comment: 'comments-blank',
  copied: 'copied-to-clipboard',
  copy: 'copy-to-clipboard',
  cursor: 'cursor2',
  discord: 'discord',
  download: 'download',
  edit: 'pencil',
  expand: 'full-screen',
  eye: 'eye',
  'eye-off': 'eye-hidden',
  'fill-bucket': 'fill-bucket',
  folder: 'folder-open',
  globe: 'globe',
  help: 'question',
  home: 'home',
  info: 'info',
  'information-circle': 'info-filled',
  lightning: 'electric',
  menu: 'hamburger',
  minus: 'minus',
  pause: 'pause',
  pencil: 'pencil',
  play: 'play',
  plus: 'plus',
  question: 'question',
  queue: 'queue',
  radiant: 'electric',
  'radiants-logo': 'radiants-logo',
  radmark: 'radiants-logo',
  refresh: 'refresh1',
  'resize-corner': 'resize-corner',
  save: 'save',
  search: 'search',
  settings: 'settings-cog',
  'text-cursor': 'cursor-text',
  trash: 'trash',
  twitter: 'twitter',
  upload: 'upload',
  warning: 'warning-filled',
  zap: 'electric',
} as const;

export type IconAliasName = keyof typeof ICON_ALIASES;
