/**
 * AUTO-GENERATED — DO NOT EDIT
 *
 * Generated by: scripts/generate-icons.ts
 * Source:       assets/icons/16px/*.svg (152 icons)
 *
 * To regenerate: pnpm generate:icons
 */

import type { ReactElement } from 'react';
import type { IconProps } from './types';

export { USDC } from './generated/16/USDC';
export { BroadcastDish } from './generated/16/broadcast-dish';
export { BrokenBattery } from './generated/16/broken-battery';
export { Calendar } from './generated/16/calendar';
export { Calendar2 } from './generated/16/calendar2';
export { Camera } from './generated/16/camera';
export { CdHorizontal } from './generated/16/cd-horizontal';
export { Cd } from './generated/16/cd';
export { CellBars } from './generated/16/cell-bars';
export { Checkmark } from './generated/16/checkmark';
export { ChevronDown } from './generated/16/chevron-down';
export { ChevronLeft } from './generated/16/chevron-left';
export { ChevronRight } from './generated/16/chevron-right';
export { Clock } from './generated/16/clock';
export { CloseFilled } from './generated/16/close-filled';
export { Close } from './generated/16/close';
export { CodeFile } from './generated/16/code-file';
export { CodeFolder } from './generated/16/code-folder';
export { CodeWindowFilled } from './generated/16/code-window-filled';
export { CodeWindow } from './generated/16/code-window';
export { Coins } from './generated/16/coins';
export { CommentsBlank } from './generated/16/comments-blank';
export { CommentsTyping } from './generated/16/comments-typing';
export { Computer } from './generated/16/computer';
export { CopiedToClipboard } from './generated/16/copied-to-clipboard';
export { CopyToClipboard } from './generated/16/copy-to-clipboard';
export { Copy } from './generated/16/copy';
export { Crosshair3 } from './generated/16/crosshair-3';
export { Crosshair1 } from './generated/16/crosshair1';
export { Crosshair2Retro } from './generated/16/crosshair2-retro';
export { Crosshair2 } from './generated/16/crosshair2';
export { Crosshair4 } from './generated/16/crosshair4';
export { CursorText } from './generated/16/cursor-text';
export { Cursor2 } from './generated/16/cursor2';
export { Cut } from './generated/16/cut';
export { Discord } from './generated/16/discord';
export { DocumentImage } from './generated/16/document-image';
export { Document } from './generated/16/document';
export { Document2 } from './generated/16/document2';
export { Download } from './generated/16/download';
export { Eject } from './generated/16/eject';
export { Electric } from './generated/16/electric';
export { EnvelopeClosed } from './generated/16/envelope-closed';
export { EnvelopeOpen } from './generated/16/envelope-open';
export { Equalizer } from './generated/16/equalizer';
export { EyeHidden } from './generated/16/eye-hidden';
export { Eye } from './generated/16/eye';
export { FilmCamera } from './generated/16/film-camera';
export { FilmStripOutline } from './generated/16/film-strip-outline';
export { FilmStrip } from './generated/16/film-strip';
export { Fire } from './generated/16/fire';
export { FolderClosed } from './generated/16/folder-closed';
export { FolderOpen } from './generated/16/folder-open';
export { FullScreen } from './generated/16/full-screen';
export { GameController } from './generated/16/game-controller';
export { Globe } from './generated/16/globe';
export { GoForward } from './generated/16/go-forward';
export { Grid3X3 } from './generated/16/grid-3x3';
export { GripHorizontal } from './generated/16/grip-horizontal';
export { GripVertical } from './generated/16/grip-vertical';
export { Hamburger } from './generated/16/hamburger';
export { HandPoint } from './generated/16/hand-point';
export { HardDrive } from './generated/16/hard-drive';
export { Headphones } from './generated/16/headphones';
export { Heart } from './generated/16/heart';
export { Home } from './generated/16/home';
export { Home2 } from './generated/16/home2';
export { Hourglass } from './generated/16/hourglass';
export { InfoFilled } from './generated/16/info-filled';
export { Info } from './generated/16/info';
export { Joystick } from './generated/16/joystick';
export { Lightbulb } from './generated/16/lightbulb';
export { Lightbulb2 } from './generated/16/lightbulb2';
export { LineChart } from './generated/16/line-chart';
export { List } from './generated/16/list';
export { LockClosed } from './generated/16/lock-closed';
export { LockOpen } from './generated/16/lock-open';
export { MicrophoneMute } from './generated/16/microphone-mute';
export { Microphone } from './generated/16/microphone';
export { Minus } from './generated/16/minus';
export { Money } from './generated/16/money';
export { Moon } from './generated/16/moon';
export { MoreHorizontal } from './generated/16/more-horizontal';
export { MoreVertical } from './generated/16/more-vertical';
export { MultipleImages } from './generated/16/multiple-images';
export { Music8thNotes } from './generated/16/music-8th-notes';
export { OutlineBox } from './generated/16/outline-box';
export { PaperPlane } from './generated/16/paper-plane';
export { Pause } from './generated/16/pause';
export { Pencil } from './generated/16/pencil';
export { PictureInPicture } from './generated/16/picture-in-picture';
export { PieChart } from './generated/16/pie-chart';
export { Play } from './generated/16/play';
export { Plug } from './generated/16/plug';
export { Plus } from './generated/16/plus';
export { Power1 } from './generated/16/power1';
export { Power2 } from './generated/16/power2';
export { Print } from './generated/16/print';
export { QuestionFilled } from './generated/16/question-filled';
export { Question } from './generated/16/question';
export { Queue } from './generated/16/queue';
export { RadMark } from './generated/16/rad-mark';
export { RadiantsLogo } from './generated/16/radiants-logo';
export { RecordPlayback } from './generated/16/record-playback';
export { RecordPlayer } from './generated/16/record-player';
export { RefreshFilled } from './generated/16/refresh-filled';
export { Refresh1 } from './generated/16/refresh1';
export { Reload } from './generated/16/reload';
export { ResizeCorner } from './generated/16/resize-corner';
export { Save2 } from './generated/16/save-2';
export { Save } from './generated/16/save';
export { Search } from './generated/16/search';
export { SeekBack } from './generated/16/seek-back';
export { SeekForward } from './generated/16/seek-forward';
export { SettingsCog } from './generated/16/settings-cog';
export { Share } from './generated/16/share';
export { SkipBack } from './generated/16/skip-back';
export { SkipForward } from './generated/16/skip-forward';
export { SkullAndCrossbones } from './generated/16/skull-and-crossbones';
export { SortDescending } from './generated/16/sort-descending';
export { SortFilterEmpty } from './generated/16/sort-filter-empty';
export { SortFilterFilled } from './generated/16/sort-filter-filled';
export { Sparkles } from './generated/16/sparkles';
export { StopPlayback } from './generated/16/stop-playback';
export { Swap } from './generated/16/swap';
export { Tape } from './generated/16/tape';
export { Telephone } from './generated/16/telephone';
export { TrashFull } from './generated/16/trash-full';
export { TrashOpen } from './generated/16/trash-open';
export { Trash } from './generated/16/trash';
export { Trophy } from './generated/16/trophy';
export { Trophy2 } from './generated/16/trophy2';
export { Tv } from './generated/16/tv';
export { Twitter } from './generated/16/twitter';
export { Upload } from './generated/16/upload';
export { UsbIcon } from './generated/16/usb-icon';
export { Usb } from './generated/16/usb';
export { Usericon } from './generated/16/usericon';
export { VolumeFaders } from './generated/16/volume-faders';
export { VolumeHigh } from './generated/16/volume-high';
export { VolumeLow } from './generated/16/volume-low';
export { VolumeMed } from './generated/16/volume-med';
export { VolumeMute } from './generated/16/volume-mute';
export { WarningFilledOutline } from './generated/16/warning-filled-outline';
export { WarningFilled } from './generated/16/warning-filled';
export { WarningHollow } from './generated/16/warning-hollow';
export { Wifi } from './generated/16/wifi';
export { WindowError } from './generated/16/window-error';
export { Windows } from './generated/16/windows';
export { Wrench } from './generated/16/wrench';
export { ZipFile } from './generated/16/zip-file';
export { ZipFile2 } from './generated/16/zip-file2';

import { USDC } from './generated/16/USDC';
import { BroadcastDish } from './generated/16/broadcast-dish';
import { BrokenBattery } from './generated/16/broken-battery';
import { Calendar } from './generated/16/calendar';
import { Calendar2 } from './generated/16/calendar2';
import { Camera } from './generated/16/camera';
import { CdHorizontal } from './generated/16/cd-horizontal';
import { Cd } from './generated/16/cd';
import { CellBars } from './generated/16/cell-bars';
import { Checkmark } from './generated/16/checkmark';
import { ChevronDown } from './generated/16/chevron-down';
import { ChevronLeft } from './generated/16/chevron-left';
import { ChevronRight } from './generated/16/chevron-right';
import { Clock } from './generated/16/clock';
import { CloseFilled } from './generated/16/close-filled';
import { Close } from './generated/16/close';
import { CodeFile } from './generated/16/code-file';
import { CodeFolder } from './generated/16/code-folder';
import { CodeWindowFilled } from './generated/16/code-window-filled';
import { CodeWindow } from './generated/16/code-window';
import { Coins } from './generated/16/coins';
import { CommentsBlank } from './generated/16/comments-blank';
import { CommentsTyping } from './generated/16/comments-typing';
import { Computer } from './generated/16/computer';
import { CopiedToClipboard } from './generated/16/copied-to-clipboard';
import { CopyToClipboard } from './generated/16/copy-to-clipboard';
import { Copy } from './generated/16/copy';
import { Crosshair3 } from './generated/16/crosshair-3';
import { Crosshair1 } from './generated/16/crosshair1';
import { Crosshair2Retro } from './generated/16/crosshair2-retro';
import { Crosshair2 } from './generated/16/crosshair2';
import { Crosshair4 } from './generated/16/crosshair4';
import { CursorText } from './generated/16/cursor-text';
import { Cursor2 } from './generated/16/cursor2';
import { Cut } from './generated/16/cut';
import { Discord } from './generated/16/discord';
import { DocumentImage } from './generated/16/document-image';
import { Document } from './generated/16/document';
import { Document2 } from './generated/16/document2';
import { Download } from './generated/16/download';
import { Eject } from './generated/16/eject';
import { Electric } from './generated/16/electric';
import { EnvelopeClosed } from './generated/16/envelope-closed';
import { EnvelopeOpen } from './generated/16/envelope-open';
import { Equalizer } from './generated/16/equalizer';
import { EyeHidden } from './generated/16/eye-hidden';
import { Eye } from './generated/16/eye';
import { FilmCamera } from './generated/16/film-camera';
import { FilmStripOutline } from './generated/16/film-strip-outline';
import { FilmStrip } from './generated/16/film-strip';
import { Fire } from './generated/16/fire';
import { FolderClosed } from './generated/16/folder-closed';
import { FolderOpen } from './generated/16/folder-open';
import { FullScreen } from './generated/16/full-screen';
import { GameController } from './generated/16/game-controller';
import { Globe } from './generated/16/globe';
import { GoForward } from './generated/16/go-forward';
import { Grid3X3 } from './generated/16/grid-3x3';
import { GripHorizontal } from './generated/16/grip-horizontal';
import { GripVertical } from './generated/16/grip-vertical';
import { Hamburger } from './generated/16/hamburger';
import { HandPoint } from './generated/16/hand-point';
import { HardDrive } from './generated/16/hard-drive';
import { Headphones } from './generated/16/headphones';
import { Heart } from './generated/16/heart';
import { Home } from './generated/16/home';
import { Home2 } from './generated/16/home2';
import { Hourglass } from './generated/16/hourglass';
import { InfoFilled } from './generated/16/info-filled';
import { Info } from './generated/16/info';
import { Joystick } from './generated/16/joystick';
import { Lightbulb } from './generated/16/lightbulb';
import { Lightbulb2 } from './generated/16/lightbulb2';
import { LineChart } from './generated/16/line-chart';
import { List } from './generated/16/list';
import { LockClosed } from './generated/16/lock-closed';
import { LockOpen } from './generated/16/lock-open';
import { MicrophoneMute } from './generated/16/microphone-mute';
import { Microphone } from './generated/16/microphone';
import { Minus } from './generated/16/minus';
import { Money } from './generated/16/money';
import { Moon } from './generated/16/moon';
import { MoreHorizontal } from './generated/16/more-horizontal';
import { MoreVertical } from './generated/16/more-vertical';
import { MultipleImages } from './generated/16/multiple-images';
import { Music8thNotes } from './generated/16/music-8th-notes';
import { OutlineBox } from './generated/16/outline-box';
import { PaperPlane } from './generated/16/paper-plane';
import { Pause } from './generated/16/pause';
import { Pencil } from './generated/16/pencil';
import { PictureInPicture } from './generated/16/picture-in-picture';
import { PieChart } from './generated/16/pie-chart';
import { Play } from './generated/16/play';
import { Plug } from './generated/16/plug';
import { Plus } from './generated/16/plus';
import { Power1 } from './generated/16/power1';
import { Power2 } from './generated/16/power2';
import { Print } from './generated/16/print';
import { QuestionFilled } from './generated/16/question-filled';
import { Question } from './generated/16/question';
import { Queue } from './generated/16/queue';
import { RadMark } from './generated/16/rad-mark';
import { RadiantsLogo } from './generated/16/radiants-logo';
import { RecordPlayback } from './generated/16/record-playback';
import { RecordPlayer } from './generated/16/record-player';
import { RefreshFilled } from './generated/16/refresh-filled';
import { Refresh1 } from './generated/16/refresh1';
import { Reload } from './generated/16/reload';
import { ResizeCorner } from './generated/16/resize-corner';
import { Save2 } from './generated/16/save-2';
import { Save } from './generated/16/save';
import { Search } from './generated/16/search';
import { SeekBack } from './generated/16/seek-back';
import { SeekForward } from './generated/16/seek-forward';
import { SettingsCog } from './generated/16/settings-cog';
import { Share } from './generated/16/share';
import { SkipBack } from './generated/16/skip-back';
import { SkipForward } from './generated/16/skip-forward';
import { SkullAndCrossbones } from './generated/16/skull-and-crossbones';
import { SortDescending } from './generated/16/sort-descending';
import { SortFilterEmpty } from './generated/16/sort-filter-empty';
import { SortFilterFilled } from './generated/16/sort-filter-filled';
import { Sparkles } from './generated/16/sparkles';
import { StopPlayback } from './generated/16/stop-playback';
import { Swap } from './generated/16/swap';
import { Tape } from './generated/16/tape';
import { Telephone } from './generated/16/telephone';
import { TrashFull } from './generated/16/trash-full';
import { TrashOpen } from './generated/16/trash-open';
import { Trash } from './generated/16/trash';
import { Trophy } from './generated/16/trophy';
import { Trophy2 } from './generated/16/trophy2';
import { Tv } from './generated/16/tv';
import { Twitter } from './generated/16/twitter';
import { Upload } from './generated/16/upload';
import { UsbIcon } from './generated/16/usb-icon';
import { Usb } from './generated/16/usb';
import { Usericon } from './generated/16/usericon';
import { VolumeFaders } from './generated/16/volume-faders';
import { VolumeHigh } from './generated/16/volume-high';
import { VolumeLow } from './generated/16/volume-low';
import { VolumeMed } from './generated/16/volume-med';
import { VolumeMute } from './generated/16/volume-mute';
import { WarningFilledOutline } from './generated/16/warning-filled-outline';
import { WarningFilled } from './generated/16/warning-filled';
import { WarningHollow } from './generated/16/warning-hollow';
import { Wifi } from './generated/16/wifi';
import { WindowError } from './generated/16/window-error';
import { Windows } from './generated/16/windows';
import { Wrench } from './generated/16/wrench';
import { ZipFile } from './generated/16/zip-file';
import { ZipFile2 } from './generated/16/zip-file2';

export const GENERATED_ICON_NAMES = [
  "USDC",
  "broadcast-dish",
  "broken-battery",
  "calendar",
  "calendar2",
  "camera",
  "cd-horizontal",
  "cd",
  "cell-bars",
  "checkmark",
  "chevron-down",
  "chevron-left",
  "chevron-right",
  "clock",
  "close-filled",
  "close",
  "code-file",
  "code-folder",
  "code-window-filled",
  "code-window",
  "coins",
  "comments-blank",
  "comments-typing",
  "computer",
  "copied-to-clipboard",
  "copy-to-clipboard",
  "copy",
  "crosshair-3",
  "crosshair1",
  "crosshair2-retro",
  "crosshair2",
  "crosshair4",
  "cursor-text",
  "cursor2",
  "cut",
  "discord",
  "document-image",
  "document",
  "document2",
  "download",
  "eject",
  "electric",
  "envelope-closed",
  "envelope-open",
  "equalizer",
  "eye-hidden",
  "eye",
  "film-camera",
  "film-strip-outline",
  "film-strip",
  "fire",
  "folder-closed",
  "folder-open",
  "full-screen",
  "game-controller",
  "globe",
  "go-forward",
  "grid-3x3",
  "grip-horizontal",
  "grip-vertical",
  "hamburger",
  "hand-point",
  "hard-drive",
  "headphones",
  "heart",
  "home",
  "home2",
  "hourglass",
  "info-filled",
  "info",
  "joystick",
  "lightbulb",
  "lightbulb2",
  "line-chart",
  "list",
  "lock-closed",
  "lock-open",
  "microphone-mute",
  "microphone",
  "minus",
  "money",
  "moon",
  "more-horizontal",
  "more-vertical",
  "multiple-images",
  "music-8th-notes",
  "outline-box",
  "paper-plane",
  "pause",
  "pencil",
  "picture-in-picture",
  "pie-chart",
  "play",
  "plug",
  "plus",
  "power1",
  "power2",
  "print",
  "question-filled",
  "question",
  "queue",
  "rad-mark",
  "radiants-logo",
  "record-playback",
  "record-player",
  "refresh-filled",
  "refresh1",
  "reload",
  "resize-corner",
  "save-2",
  "save",
  "search",
  "seek-back",
  "seek-forward",
  "settings-cog",
  "share",
  "skip-back",
  "skip-forward",
  "skull-and-crossbones",
  "sort-descending",
  "sort-filter-empty",
  "sort-filter-filled",
  "sparkles",
  "stop-playback",
  "swap",
  "tape",
  "telephone",
  "trash-full",
  "trash-open",
  "trash",
  "trophy",
  "trophy2",
  "tv",
  "twitter",
  "upload",
  "usb-icon",
  "usb",
  "usericon",
  "volume-faders",
  "volume-high",
  "volume-low",
  "volume-med",
  "volume-mute",
  "warning-filled-outline",
  "warning-filled",
  "warning-hollow",
  "wifi",
  "window-error",
  "windows",
  "wrench",
  "zip-file",
  "zip-file2"
] as const;

export type GeneratedIconName = (typeof GENERATED_ICON_NAMES)[number];

export const ICON_BY_NAME: Record<string, (props: IconProps) => ReactElement> = {
  'USDC': USDC,
  'broadcast-dish': BroadcastDish,
  'broken-battery': BrokenBattery,
  'calendar': Calendar,
  'calendar2': Calendar2,
  'camera': Camera,
  'cd-horizontal': CdHorizontal,
  'cd': Cd,
  'cell-bars': CellBars,
  'checkmark': Checkmark,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'clock': Clock,
  'close-filled': CloseFilled,
  'close': Close,
  'code-file': CodeFile,
  'code-folder': CodeFolder,
  'code-window-filled': CodeWindowFilled,
  'code-window': CodeWindow,
  'coins': Coins,
  'comments-blank': CommentsBlank,
  'comments-typing': CommentsTyping,
  'computer': Computer,
  'copied-to-clipboard': CopiedToClipboard,
  'copy-to-clipboard': CopyToClipboard,
  'copy': Copy,
  'crosshair-3': Crosshair3,
  'crosshair1': Crosshair1,
  'crosshair2-retro': Crosshair2Retro,
  'crosshair2': Crosshair2,
  'crosshair4': Crosshair4,
  'cursor-text': CursorText,
  'cursor2': Cursor2,
  'cut': Cut,
  'discord': Discord,
  'document-image': DocumentImage,
  'document': Document,
  'document2': Document2,
  'download': Download,
  'eject': Eject,
  'electric': Electric,
  'envelope-closed': EnvelopeClosed,
  'envelope-open': EnvelopeOpen,
  'equalizer': Equalizer,
  'eye-hidden': EyeHidden,
  'eye': Eye,
  'film-camera': FilmCamera,
  'film-strip-outline': FilmStripOutline,
  'film-strip': FilmStrip,
  'fire': Fire,
  'folder-closed': FolderClosed,
  'folder-open': FolderOpen,
  'full-screen': FullScreen,
  'game-controller': GameController,
  'globe': Globe,
  'go-forward': GoForward,
  'grid-3x3': Grid3X3,
  'grip-horizontal': GripHorizontal,
  'grip-vertical': GripVertical,
  'hamburger': Hamburger,
  'hand-point': HandPoint,
  'hard-drive': HardDrive,
  'headphones': Headphones,
  'heart': Heart,
  'home': Home,
  'home2': Home2,
  'hourglass': Hourglass,
  'info-filled': InfoFilled,
  'info': Info,
  'joystick': Joystick,
  'lightbulb': Lightbulb,
  'lightbulb2': Lightbulb2,
  'line-chart': LineChart,
  'list': List,
  'lock-closed': LockClosed,
  'lock-open': LockOpen,
  'microphone-mute': MicrophoneMute,
  'microphone': Microphone,
  'minus': Minus,
  'money': Money,
  'moon': Moon,
  'more-horizontal': MoreHorizontal,
  'more-vertical': MoreVertical,
  'multiple-images': MultipleImages,
  'music-8th-notes': Music8thNotes,
  'outline-box': OutlineBox,
  'paper-plane': PaperPlane,
  'pause': Pause,
  'pencil': Pencil,
  'picture-in-picture': PictureInPicture,
  'pie-chart': PieChart,
  'play': Play,
  'plug': Plug,
  'plus': Plus,
  'power1': Power1,
  'power2': Power2,
  'print': Print,
  'question-filled': QuestionFilled,
  'question': Question,
  'queue': Queue,
  'rad-mark': RadMark,
  'radiants-logo': RadiantsLogo,
  'record-playback': RecordPlayback,
  'record-player': RecordPlayer,
  'refresh-filled': RefreshFilled,
  'refresh1': Refresh1,
  'reload': Reload,
  'resize-corner': ResizeCorner,
  'save-2': Save2,
  'save': Save,
  'search': Search,
  'seek-back': SeekBack,
  'seek-forward': SeekForward,
  'settings-cog': SettingsCog,
  'share': Share,
  'skip-back': SkipBack,
  'skip-forward': SkipForward,
  'skull-and-crossbones': SkullAndCrossbones,
  'sort-descending': SortDescending,
  'sort-filter-empty': SortFilterEmpty,
  'sort-filter-filled': SortFilterFilled,
  'sparkles': Sparkles,
  'stop-playback': StopPlayback,
  'swap': Swap,
  'tape': Tape,
  'telephone': Telephone,
  'trash-full': TrashFull,
  'trash-open': TrashOpen,
  'trash': Trash,
  'trophy': Trophy,
  'trophy2': Trophy2,
  'tv': Tv,
  'twitter': Twitter,
  'upload': Upload,
  'usb-icon': UsbIcon,
  'usb': Usb,
  'usericon': Usericon,
  'volume-faders': VolumeFaders,
  'volume-high': VolumeHigh,
  'volume-low': VolumeLow,
  'volume-med': VolumeMed,
  'volume-mute': VolumeMute,
  'warning-filled-outline': WarningFilledOutline,
  'warning-filled': WarningFilled,
  'warning-hollow': WarningHollow,
  'wifi': Wifi,
  'window-error': WindowError,
  'windows': Windows,
  'wrench': Wrench,
  'zip-file': ZipFile,
  'zip-file2': ZipFile2,
};
