/**
 * Icon Size Map
 *
 * Maps canonical icon names between 16px and 24px icon sets.
 * When an icon is requested at a different size than its native set,
 * this map provides the equivalent icon in the target set.
 *
 * Only icons with a clear semantic match are included. Brand icons
 * (rad-mark, radiants-logo, USDC) and geometric primitives
 * (chevron-*, close, plus, minus) with no 24px equivalent are omitted.
 */

/** Map 16px icon names → their 24px equivalents */
export const ICON_16_TO_24: Record<string, string> = {
  'broadcast-dish': 'interface-essential-satellite',
  'broken-battery': 'computers-devices-electronics-battery-charge',
  'calendar': 'interface-essential-calendar-date',
  'calendar2': 'interface-essential-calendar-appointment',
  'camera': 'photography-camera-1',
  'cd': 'computers-devices-electronicscd-disk',
  'cell-bars': 'phone-signal-full',
  'checkmark': 'business-product-check',
  'clock': 'interface-essential-clock',
  'code-file': 'coding-apps-websites-programming-hold-code',
  'code-folder': 'interface-essential-hierarchy-files',
  'code-window': 'coding-apps-websites-programming-browser',
  'code-window-filled': 'coding-apps-websites',
  'coins': 'business-money-coin-currency',
  'comments-blank': 'interface-essential-message',
  'comments-typing': 'email-chat-think',
  'computer': 'computers-devices-electronics-desktop',
  'copied-to-clipboard': 'content-files-sticky-notepad-2',
  'copy-to-clipboard': 'content-files-sticky-notepad-1',
  'crosshair-3': 'interface-essential-cursor-click-point',
  'crosshair1': 'map-navigation-location-focus',
  'cursor-text': 'interface-essential-find-text',
  'cursor2': 'interface-essential-cursor',
  'cut': 'interface-essential-scisor',
  'discord': 'logo-discord',
  'document': 'content-files-note',
  'document-image': 'photography-file-picture',
  'document2': 'content-files-notepad',
  'download': 'internet-network-download',
  'eject': 'interface-essential-flip-vertical-up',
  'electric': 'interface-essential-flash',
  'envelope-closed': 'email-envelope-close',
  'envelope-open': 'email-envelope-open',
  'equalizer': 'interface-essential-setting-slide',
  'eye': 'interface-essential-view-eye',
  'eye-hidden': 'interface-essential-iris-scan',
  'film-camera': 'entertainment-events-hobbies-film-camrea',
  'film-strip': 'entertainment-events-hobbies-film-roll',
  'film-strip-outline': 'entertainment-events-hobbies-film-player',
  'fire': 'social-rewards-trends-hot-flame',
  'folder-closed': 'content-files-archive-books-1',
  'folder-open': 'content-files-folder-open',
  'full-screen': 'interface-essential-expand-1',
  'game-controller': 'entertainment-events-hobbies-game-machines-arcade-1',
  'globe': 'interface-essential-global-public',
  'go-forward': 'interface-essential-navigation-right-circle-1',
  'grid-3x3': 'interface-essential-dial-pad-1',
  'grip-horizontal': 'interface-essential-scroll-horizontal',
  'grip-vertical': 'interface-essential-scroll-vertical',
  'hamburger': 'interface-essential-navigation-menu-1',
  'hand-point': 'hand-point',
  'hard-drive': 'computers-devices-electronics-harddisk',
  'headphones': 'music-headphones-human',
  'heart': 'interface-essential-heart-favorite',
  'home': 'interface-essential-home-1',
  'home2': 'interface-essential-home-2',
  'hourglass': 'interface-essential-waiting-hourglass-loading',
  'info': 'interface-essential-information-circle-1',
  'info-filled': 'interface-essential-information-circle-2',
  'joystick': 'entertainment-events-hobbies-game-machines-arcade-2',
  'lightbulb': 'interface-essential-light-bulb',
  'lightbulb2': 'ecology-organic-sun-growth',
  'line-chart': 'interface-essential-stat',
  'list': 'interface-essential-list',
  'lock-closed': 'interface-essential-lock',
  'lock-open': 'interface-essential-lock-1',
  'microphone': 'interface-essential-microphone',
  'microphone-mute': 'music-microphone-off',
  'money': 'business-products-money',
  'moon': 'weather-moon',
  'multiple-images': 'photography-frame-picture',
  'music-8th-notes': 'music-notes-music-1',
  'newspaper': 'content-files-newspaper',
  'paper-plane': 'send-email',
  'pause': 'video-movies-square-off',
  'pencil': 'design-pencil',
  'picture-in-picture': 'photography-photo-image',
  'pie-chart': 'interface-essential-pie-chart-poll-report-1',
  'play': 'video-movies-play',
  'plug': 'ecology-clean-car-cable-charge',
  'power1': 'interface-essential-switch-on',
  'power2': 'interface-essential-switch-off',
  'print': 'interface-essential-print',
  'question': 'interface-essential-question-help-circle-1',
  'question-filled': 'interface-essential-question-help-circle-2',
  'record-playback': 'interface-essential-loading-circle-1',
  'record-player': 'entertainment-events-hobbies-record-player',
  'refresh-filled': 'interface-essential-refresh',
  'refresh1': 'interface-essential-refresh',
  'reload': 'interface-essential-synchronize-arrows-square-2',
  'resize-corner': 'interface-essential-expand-2',
  'save': 'interface-essential-floppy-disk',
  'save-2': 'interface-essential-floppy-disk',
  'search': 'interface-essential-search-1',
  'settings-cog': 'interface-essential-setting-cog',
  'share': 'interface-essential-share-1',
  'skull-and-crossbones': 'interface-essential-skull-1',
  'sort-descending': 'interface-essential-poll',
  'sort-filter-empty': 'interface-essential-filter',
  'sort-filter-filled': 'interface-essential-filter',
  'sparkles': 'photography-retouch-wand-star',
  'stop-playback': 'interface-essential-stop-sign-1',
  'swap': 'interface-essential-synchronize-arrows-square-1',
  'tape': 'computers-devices-electronics-tape-cassette',
  'telephone': 'vintage-phone',
  'trash': 'interface-essential-bin',
  'trophy': 'interface-essential-trophy',
  'trophy2': 'social-rewards-reward-gift',
  'tv': 'computers-devices-electronics-television-vintage',
  'twitter': 'logo-twitter',
  'upload': 'internet-network-upload',
  'usb': 'computers-devices-electronics-flash-drive-1',
  'usericon': 'interface-essential-profile-male',
  'volume-high': 'interface-essential-sound',
  'volume-mute': 'music-speaker',
  'warning-filled': 'interface-essential-alert-triangle-1',
  'warning-filled-outline': 'interface-essential-alert-triangle-2',
  'warning-hollow': 'interface-essential-alert-caution',
  'wifi': 'interface-essential-wifi-signal',
  'window-error': 'coding-apps-websites-404-error',
  'windows': 'coding-apps-websites-setting-computer',
  'wrench': 'interface-essential-wrench-1',
  'zip-file': 'content-files-archive-books-2',
  'zip-file2': 'content-files-archive-books-3',
};

/** Reverse map: 24px icon names → their 16px equivalents */
export const ICON_24_TO_16: Record<string, string> = Object.fromEntries(
  Object.entries(ICON_16_TO_24).map(([k, v]) => [v, k])
);

/** Check if a name belongs to the 16px set */
export function is16pxIcon(name: string): boolean {
  return name in ICON_16_TO_24 || !name.includes('-');
}
