#!/usr/bin/env node

/**
 * generate-blocknote-blocks.ts
 *
 * Reads componentMetaIndex, filters for components with blockNote.enabled,
 * and emits packages/radiants/generated/blocknote-blocks.tsx with:
 *   - createReactBlockSpec call per component
 *   - rdnaBlockSpecs record (spread into BlockNoteSchema.create)
 *   - rdnaSlashMenuDescriptors array (plain data for slash menu hydration)
 */

import { existsSync, readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { createHash } from "node:crypto";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { componentMetaIndex } from "../meta/index.ts";
import type { ComponentMeta, PropDef, BlockNoteMeta } from "../../preview/src/types.ts";

const __dirname = dirname(fileURLToPath(import.meta.url));
const PACKAGE_ROOT = resolve(__dirname, "..");
const OUTPUT_DIR = resolve(PACKAGE_ROOT, "generated");
const OUTPUT_PATH = resolve(OUTPUT_DIR, "blocknote-blocks.tsx");

// ============================================================================
// Types
// ============================================================================

interface BlockNoteEntry {
  name: string;
  type: string; // lowercased name
  meta: ComponentMeta<Record<string, unknown>>;
  blockNote: BlockNoteMeta;
}

interface SlashMenuDescriptor {
  type: string;
  title: string;
  subtext: string;
  aliases: string[];
  icon: string;
  group: string;
  defaultProps: Record<string, unknown>;
}

// ============================================================================
// Helpers
// ============================================================================

function fileHash(content: string): string {
  return createHash("sha1").update(content).digest("hex");
}

/**
 * Map a ComponentMeta PropDef to a BlockNote propSchema entry.
 * Returns the stringified JS object literal for the prop schema value.
 */
function propDefToBlockNote(propDef: PropDef): string | null {
  if (propDef.type === "enum" && propDef.values && propDef.values.length > 0) {
    const defaultVal = propDef.default ?? propDef.values[0];
    const valuesStr = propDef.values.map((v) => `'${v}'`).join(", ");
    return `{ default: '${defaultVal}' as const, values: [${valuesStr}] as const }`;
  }
  if (propDef.type === "string") {
    const defaultVal = propDef.default ?? "";
    return `{ default: '${defaultVal}' }`;
  }
  if (propDef.type === "boolean") {
    const defaultVal = propDef.default ?? false;
    return `{ default: ${defaultVal} }`;
  }
  // Skip function, node, number, array — not representable in BlockNote
  return null;
}

// ============================================================================
// Collect entries
// ============================================================================

const entries: BlockNoteEntry[] = [];

for (const indexEntry of Object.values(componentMetaIndex)) {
  const meta = indexEntry.meta as ComponentMeta<Record<string, unknown>>;
  if (!meta.blockNote?.enabled) continue;

  entries.push({
    name: meta.name,
    type: meta.name.toLowerCase(),
    meta,
    blockNote: meta.blockNote,
  });
}

entries.sort((a, b) => a.name.localeCompare(b.name));

if (entries.length === 0) {
  console.log("No components with blockNote.enabled — skipping generation.");
  process.exit(0);
}

// ============================================================================
// Generate code
// ============================================================================

const lines: string[] = [];

lines.push(`// AUTO-GENERATED — DO NOT EDIT`);
lines.push(`// Generated by: scripts/generate-blocknote-blocks.ts`);
lines.push(`// To regenerate: pnpm --filter @rdna/radiants generate:blocknote`);
lines.push(`// Components: ${entries.map((e) => e.name).join(", ")}`);
lines.push(``);

// Imports — BlockNote
lines.push(`import { createReactBlockSpec } from '@blocknote/react';`);
lines.push(``);

// Imports — RDNA components (for auto-generated renders, no custom render file)
const simpleEntries = entries.filter((e) => !e.blockNote.render);
const customEntries = entries.filter((e) => e.blockNote.render);

if (simpleEntries.length > 0) {
  const imports = simpleEntries.map((e) => e.name).join(", ");
  lines.push(`import { ${imports} } from '../components/core';`);
}

// Imports — custom render functions (paths are relative to packages/radiants/,
// but the generated file lives in generated/, so prefix with ../)
for (const entry of customEntries) {
  const fnName = `render${entry.name}Block`;
  const renderPath = entry.blockNote.render!.replace(/^\.\//, '../');
  lines.push(`import { ${fnName} } from '${renderPath}';`);
}

lines.push(``);

// ============================================================================
// Block specs
// ============================================================================

for (const entry of entries) {
  const { name, type, meta, blockNote } = entry;
  const content = blockNote.content ?? "inline";
  const fnName = `${type}Block`;

  // Build propSchema
  const propSchemaEntries: string[] = [];
  if (blockNote.propSchema) {
    for (const [key, { prop }] of Object.entries(blockNote.propSchema)) {
      const propDef = meta.props[prop];
      if (!propDef) {
        console.warn(`  ⚠ ${name}: prop "${prop}" not found in meta.props — skipping`);
        continue;
      }
      const bnProp = propDefToBlockNote(propDef);
      if (!bnProp) {
        console.warn(`  ⚠ ${name}: prop "${prop}" (type: ${propDef.type}) not mappable — skipping`);
        continue;
      }
      propSchemaEntries.push(`    ${key}: ${bnProp},`);
    }
  }

  lines.push(`export const ${fnName} = createReactBlockSpec(`);
  lines.push(`  {`);
  lines.push(`    type: '${type}' as const,`);

  if (propSchemaEntries.length > 0) {
    lines.push(`    propSchema: {`);
    lines.push(...propSchemaEntries);
    lines.push(`    },`);
  } else {
    lines.push(`    propSchema: {},`);
  }

  lines.push(`    content: '${content}' as const,`);
  lines.push(`  },`);
  lines.push(`  {`);

  if (blockNote.render) {
    // Custom render function — explicit any to avoid deep BlockNote generic noise
    lines.push(`    render: (props: any) => render${name}Block(props),`);
  } else if (content === "inline") {
    // Inline content — component wraps editable contentRef
    const hasChildren = Boolean(meta.slots?.['children']);
    if (hasChildren) {
      lines.push(`    render: ({ contentRef }: any) => (`);
      lines.push(`      <${name}><span ref={contentRef} /></${name}>`);
      lines.push(`    ),`);
    } else {
      // No children slot but content: inline — just provide contentRef in a wrapper
      lines.push(`    render: ({ contentRef }: any) => (`);
      lines.push(`      <div><${name} /><span ref={contentRef} /></div>`);
      lines.push(`    ),`);
    }
  } else {
    // content: "none" — static block, no editable text
    const hasChildren = Boolean(meta.slots?.['children']);

    // Build required prop defaults for components with required props
    const requiredProps: string[] = [];
    for (const [propName, propDef] of Object.entries(meta.props)) {
      if (!propDef.required) continue;
      if (propDef.type === "function") continue; // skip callbacks
      const defaultVal = propDef.default;
      if (defaultVal !== undefined) {
        requiredProps.push(`${propName}={${JSON.stringify(defaultVal)}}`);
      } else if (propDef.type === "string") {
        requiredProps.push(`${propName}="${propName}"`);
      } else if (propDef.type === "number") {
        requiredProps.push(`${propName}={0}`);
      } else if (propDef.type === "boolean") {
        requiredProps.push(`${propName}={false}`);
      } else if (propDef.type === "enum" && propDef.values?.[0] !== undefined) {
        requiredProps.push(`${propName}="${propDef.values[0]}"`);
      }
    }
    const propsStr = requiredProps.length > 0 ? ` ${requiredProps.join(" ")}` : "";

    if (hasChildren) {
      lines.push(`    render: () => <${name}${propsStr}>${name}</${name}>,`);
    } else {
      lines.push(`    render: () => <${name}${propsStr} />,`);
    }
  }

  lines.push(`  },`);
  lines.push(`);`);
  lines.push(``);
}

// ============================================================================
// Combined exports
// ============================================================================

// rdnaBlockSpecs — record to spread into BlockNoteSchema.create
lines.push(`/** Spread into BlockNoteSchema.create({ blockSpecs: { ...defaultBlockSpecs, ...rdnaBlockSpecs } }) */`);
lines.push(`export const rdnaBlockSpecs = {`);
for (const entry of entries) {
  lines.push(`  ${entry.type}: ${entry.type}Block(),`);
}
lines.push(`};`);
lines.push(``);

// Slash menu descriptors — plain data, hydrated at runtime
lines.push(`/** Plain descriptors — hydrate into DefaultReactSuggestionItem at runtime with editor instance */`);
lines.push(`export interface RdnaSlashMenuDescriptor {`);
lines.push(`  type: string;`);
lines.push(`  title: string;`);
lines.push(`  subtext: string;`);
lines.push(`  aliases: string[];`);
lines.push(`  icon: string;`);
lines.push(`  group: string;`);
lines.push(`  defaultProps: Record<string, unknown>;`);
lines.push(`}`);
lines.push(``);
lines.push(`export const rdnaSlashMenuDescriptors: RdnaSlashMenuDescriptor[] = [`);

for (const entry of entries) {
  const sm = entry.blockNote.slashMenu ?? {};
  const title = sm.title ?? entry.name;
  const subtext = sm.subtext ?? entry.meta.description.slice(0, 60);
  const aliases = JSON.stringify(sm.aliases ?? [entry.type]);
  const icon = sm.icon ?? "plus";
  const group = sm.group ?? "RDNA";

  // Build default props from the first enum value of each prop
  const defaultProps: Record<string, unknown> = {};
  if (entry.blockNote.propSchema) {
    for (const [key, { prop }] of Object.entries(entry.blockNote.propSchema)) {
      const propDef = entry.meta.props[prop];
      if (propDef?.default !== undefined) {
        defaultProps[key] = propDef.default;
      } else if (propDef?.values?.[0] !== undefined) {
        defaultProps[key] = propDef.values[0];
      }
    }
  }

  lines.push(`  {`);
  lines.push(`    type: '${entry.type}',`);
  lines.push(`    title: '${title}',`);
  lines.push(`    subtext: '${subtext}',`);
  lines.push(`    aliases: ${aliases},`);
  lines.push(`    icon: '${icon}',`);
  lines.push(`    group: '${group}',`);
  lines.push(`    defaultProps: ${JSON.stringify(defaultProps)},`);
  lines.push(`  },`);
}

lines.push(`];`);
lines.push(``);

// ============================================================================
// Write output
// ============================================================================

const output = lines.join("\n");

if (!existsSync(OUTPUT_DIR)) {
  mkdirSync(OUTPUT_DIR, { recursive: true });
}

// Change detection — skip write if content unchanged
if (existsSync(OUTPUT_PATH)) {
  const existing = readFileSync(OUTPUT_PATH, "utf8");
  if (fileHash(existing) === fileHash(output)) {
    console.log(`blocknote-blocks.tsx unchanged (${entries.length} components)`);
    process.exit(0);
  }
}

writeFileSync(OUTPUT_PATH, output, "utf8");
console.log(`Wrote ${OUTPUT_PATH} (${entries.length} components: ${entries.map((e) => e.name).join(", ")})`);
