#!/usr/bin/env node

/**
 * generate-icons.mjs
 *
 * Reads all SVG files from assets/icons/ and generates a single
 * icons/generated.tsx with inline React icon components.
 *
 * Usage:  node scripts/generate-icons.mjs
 * Output: icons/generated.tsx
 */

import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join, basename, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const ICONS_DIR = join(ROOT, 'assets', 'icons');
const OUTPUT = join(ROOT, 'icons', 'generated.tsx');

// --------------------------------------------------------------------------
// Name overrides: kebab-case filename → exact PascalCase export
// --------------------------------------------------------------------------
const NAME_OVERRIDES = {
  'grid-3x3': 'Grid3X3',
  'cd': 'Cd',
  'tv': 'Tv',
  'usb': 'Usb',
  'USDC': 'USDC',
};

// --------------------------------------------------------------------------
// Helpers
// --------------------------------------------------------------------------

/** Convert kebab-case to PascalCase: "bar-chart" → "BarChart" */
function toPascalCase(str) {
  return str
    .split('-')
    .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
    .join('');
}

/** Get the component name for a file */
function componentName(filename) {
  const stem = basename(filename, '.svg');
  return NAME_OVERRIDES[stem] ?? toPascalCase(stem);
}

/** HTML attribute → JSX attribute */
const ATTR_MAP = {
  'fill-rule': 'fillRule',
  'clip-rule': 'clipRule',
  'stroke-width': 'strokeWidth',
  'stroke-linecap': 'strokeLinecap',
  'stroke-linejoin': 'strokeLinejoin',
  'stroke-dasharray': 'strokeDasharray',
  'stroke-dashoffset': 'strokeDashoffset',
  'font-size': 'fontSize',
  'font-family': 'fontFamily',
  'text-anchor': 'textAnchor',
  'dominant-baseline': 'dominantBaseline',
  'class': 'className',
};

function htmlAttrsToJsx(str) {
  for (const [html, jsx] of Object.entries(ATTR_MAP)) {
    str = str.replaceAll(html, jsx);
  }
  return str;
}

/** Extract viewBox from <svg> tag, default "0 0 16 16" */
function extractViewBox(svg) {
  const match = svg.match(/viewBox="([^"]+)"/);
  return match ? match[1] : '0 0 16 16';
}

/** Extract inner content between <svg> and </svg> */
function extractInner(svg) {
  const open = svg.indexOf('>') + 1;
  const close = svg.lastIndexOf('</svg>');
  if (close === -1) return '';
  return svg.slice(open, close).trim();
}

// --------------------------------------------------------------------------
// Main
// --------------------------------------------------------------------------

const files = readdirSync(ICONS_DIR)
  .filter((f) => f.endsWith('.svg'))
  .sort();

console.log(`Found ${files.length} SVG files in assets/icons/`);

const components = [];
const exports = [];

for (const file of files) {
  const raw = readFileSync(join(ICONS_DIR, file), 'utf-8').trim();
  const name = componentName(file);
  const viewBox = extractViewBox(raw);
  let inner = extractInner(raw);
  inner = htmlAttrsToJsx(inner);

  components.push(`
export const ${name} = ({ size = 16, className = '', ...props }: IconProps) => (
  <svg width={size} height={size} viewBox="${viewBox}" fill="currentColor" className={className} {...props}>
    ${inner}
  </svg>
);
${name}.displayName = '${name}';`);

  exports.push(name);
}

const output = `/**
 * AUTO-GENERATED — DO NOT EDIT
 *
 * Generated by: scripts/generate-icons.mjs
 * Source:       assets/icons/*.svg (${files.length} icons)
 *
 * To regenerate: pnpm generate:icons
 */

import type { IconProps } from './types';
${components.join('\n')}

/** All generated icon names (kebab-case, matching SVG filenames) */
export const GENERATED_ICON_NAMES = ${JSON.stringify(files.map((f) => basename(f, '.svg')), null, 2)} as const;

export type GeneratedIconName = (typeof GENERATED_ICON_NAMES)[number];
`;

writeFileSync(OUTPUT, output, 'utf-8');
console.log(`Generated ${exports.length} icon components → icons/generated.tsx`);
console.log('Exports:', exports.join(', '));
