
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * Greet someone by name - basic test command
 */
async greet(name: string) : Promise<string> {
    return await TAURI_INVOKE("greet", { name });
},
/**
 * Get the current application version
 */
async getVersion() : Promise<VersionInfo> {
    return await TAURI_INVOKE("get_version");
},
/**
 * Validate that a folder is a valid project (contains package.json or tsconfig.json)
 */
async validateProject(path: string) : Promise<ProjectValidation> {
    return await TAURI_INVOKE("validate_project", { path });
},
/**
 * Parse a single TSX component file and return component information
 */
async parseComponent(path: string) : Promise<Result<ComponentInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("parse_component", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Scan a directory for TSX components and return all found components
 */
async scanComponents(dir: string) : Promise<Result<ComponentInfo[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("scan_components", { dir }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Parse a CSS file and extract theme tokens from @theme blocks
 */
async parseTokens(cssPath: string) : Promise<Result<ThemeTokens, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("parse_tokens", { cssPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Scan a directory for design system violations
 */
async scanViolations(dir: string) : Promise<Result<ViolationInfo[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("scan_violations", { dir }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Detect violations in a single file
 */
async detectViolations(path: string) : Promise<Result<ViolationInfo[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("detect_violations", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Start watching a directory for file changes
 * Emits "file-changed" events to the frontend
 */
async startWatcher(path: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_watcher", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Stop the file watcher
 */
async stopWatcher() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_watcher") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get the currently watched path, if any
 */
async getWatchedPath() : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_watched_path") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Write a text change to a source file
 * 
 * This command reads the file, replaces the old text with new text at the specified line,
 * and writes the file back. It's designed for Text Edit Mode's direct write functionality.
 */
async writeTextChange(path: string, line: number, oldText: string, newText: string) : Promise<TextChangeResult> {
    return await TAURI_INVOKE("write_text_change", { path, line, oldText, newText });
},
/**
 * Get file information including modification time
 * 
 * Used to check if a file has been modified externally before writing.
 */
async getFileInfo(path: string) : Promise<FileInfo> {
    return await TAURI_INVOKE("get_file_info", { path });
},
/**
 * Revert a text change (for undo functionality)
 * 
 * This is essentially the same as write_text_change but with swapped old/new text.
 */
async revertTextChange(path: string, line: number, currentText: string, originalText: string) : Promise<TextChangeResult> {
    return await TAURI_INVOKE("revert_text_change", { path, line, currentText, originalText });
},
/**
 * Detect a project and extract its configuration
 */
async detectProject(path: string) : Promise<ProjectDetectionResult> {
    return await TAURI_INVOKE("detect_project", { path });
},
/**
 * Start the dev server for a project
 */
async startDevServer(path: string, command: string, port: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_dev_server", { path, command, port }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Stop the dev server
 */
async stopDevServer() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_dev_server") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get the current dev server status
 */
async getDevServerStatus() : Promise<Result<ServerStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_dev_server_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get recent dev server logs
 */
async getDevServerLogs() : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_dev_server_logs") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Check if the dev server is healthy (port responding)
 */
async checkDevServerHealth(port: number) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_dev_server_health", { port }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

/**
 * Represents an extracted component with its metadata
 */
export type ComponentInfo = { name: string; file: string; line: number; props: PropInfo[]; defaultExport: boolean; unionTypes: UnionTypeInfo[] }
/**
 * Information about a file's current state
 */
export type FileInfo = { 
/**
 * File modification time (Unix timestamp in milliseconds)
 */
modifiedAt: number; 
/**
 * File exists
 */
exists: boolean }
/**
 * Package manager detected from lockfile
 */
export type PackageManager = "pnpm" | "yarn" | "npm"
/**
 * Result of project detection
 */
export type ProjectDetectionResult = { success: boolean; project: ProjectInfo | null; error: string | null }
/**
 * Information about a detected project
 */
export type ProjectInfo = { path: string; name: string; projectType: ProjectType; packageManager: PackageManager; devCommand: string; devPort: number; nextVersion: string | null; hasBridge: boolean }
/**
 * Project type detected from dependencies
 */
export type ProjectType = "nextjs" | "unknown"
/**
 * Result of validating a project folder
 */
export type ProjectValidation = { valid: boolean; project_name: string | null; error: string | null }
/**
 * Represents a component prop with its type and optional default value
 */
export type PropInfo = { name: string; type: string; 
/**
 * Whether the prop is required (no default value and not optional)
 */
required: boolean; default?: string | null; doc?: string | null; 
/**
 * Inferred control type for UI: "text", "number", "boolean", "select", "slot"
 */
controlType?: string | null; 
/**
 * Options for select control (from union types)
 */
options?: string[] | null }
/**
 * Server state for display
 */
export type ServerStatus = { state: "stopped" } | { state: "starting"; logs: string[] } | { state: "running"; port: number; pid: number } | { state: "error"; message: string; logs: string[] }
/**
 * Result of a text change operation
 */
export type TextChangeResult = { 
/**
 * Whether the change was successfully written
 */
success: boolean; 
/**
 * Error message if failed
 */
error: string | null; 
/**
 * New file modification time (Unix timestamp in milliseconds)
 */
modifiedAt: number | null }
/**
 * Theme tokens extracted from @theme blocks
 */
export type ThemeTokens = { 
/**
 * Tokens from @theme inline (internal reference, not exported as utilities)
 */
inline: Partial<{ [key in string]: string }>; 
/**
 * Tokens from @theme (exported as Tailwind utilities)
 */
public: Partial<{ [key in string]: string }> }
/**
 * Represents a union type alias like `type ButtonVariant = 'primary' | 'secondary'`
 */
export type UnionTypeInfo = { name: string; values: string[]; line: number }
/**
 * Application version info returned by get_version command
 */
export type VersionInfo = { version: string; tauri_version: string }
/**
 * Represents a design system violation
 */
export type ViolationInfo = { file: string; line: number; column: number; severity: ViolationSeverity; message: string; codeSnippet: string; suggestion?: string | null }
/**
 * Violation severity levels
 */
export type ViolationSeverity = "warning" | "error"

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
