import type { PlaygroundPreset } from './types';

export const PRESETS: PlaygroundPreset[] = [
  {
    name: 'Classic Ink',
    description: 'Ink on cream — the default RDNA look',
    state: {
      pat: 'checkerboard',
      color: 'var(--color-ink)',
      bg: 'transparent',
      scale: 2,
      hoverColor: 'var(--color-ink)',
      hoverBg: 'var(--color-sun-yellow)',
      hoverScale: 1.02,
      hoverOpacity: 1,
      pressedColor: 'var(--color-ink)',
      pressedBg: 'var(--color-sun-yellow)',
      pressedScale: 0.98,
      pressedTranslateY: 1,
      glowEnabled: true,
      glowCenter: 'var(--color-sun-yellow)',
      glowSpread: 40,
      glowFade: 80,
    },
  },
  {
    name: 'Sun Glow',
    description: 'Yellow patterns with warm radial glow',
    state: {
      pat: 'diagonal-dots',
      color: 'var(--color-sun-yellow)',
      bg: 'var(--color-ink)',
      scale: 2,
      hoverColor: 'var(--color-sun-yellow)',
      hoverBg: 'var(--color-ink)',
      hoverScale: 1.03,
      hoverOpacity: 1,
      pressedColor: 'var(--color-sunset-fuzz)',
      pressedBg: 'var(--color-ink)',
      pressedScale: 0.97,
      pressedTranslateY: 1,
      glowEnabled: true,
      glowCenter: 'var(--color-sun-yellow)',
      glowSpread: 30,
      glowFade: 70,
    },
  },
  {
    name: 'Neon Grid',
    description: 'Mint on ink — cyberpunk terminal',
    state: {
      pat: 'grid',
      color: 'var(--color-mint)',
      bg: 'var(--color-ink)',
      scale: 3,
      hoverColor: 'var(--color-mint)',
      hoverBg: 'var(--color-ink)',
      hoverScale: 1.01,
      hoverOpacity: 0.9,
      pressedColor: 'var(--color-sky-blue)',
      pressedBg: 'var(--color-ink)',
      pressedScale: 0.99,
      pressedTranslateY: 0.5,
      glowEnabled: true,
      glowCenter: 'var(--color-mint)',
      glowSpread: 35,
      glowFade: 75,
    },
  },
  {
    name: 'Cream Paper',
    description: 'Subtle texture for light backgrounds',
    state: {
      pat: 'dust',
      color: 'var(--color-ink)',
      bg: 'var(--color-cream)',
      scale: 1,
      hoverColor: 'var(--color-ink)',
      hoverBg: 'var(--color-cream)',
      hoverScale: 1,
      hoverOpacity: 0.7,
      pressedColor: 'var(--color-ink)',
      pressedBg: 'var(--color-cream)',
      pressedScale: 1,
      pressedTranslateY: 0,
      glowEnabled: false,
      glowCenter: 'var(--color-sun-yellow)',
      glowSpread: 40,
      glowFade: 80,
    },
  },
  {
    name: 'Warm Hover',
    description: 'Sunset tones on hover interaction',
    state: {
      pat: 'confetti',
      color: 'var(--color-ink)',
      bg: 'transparent',
      scale: 2,
      hoverColor: 'var(--color-sunset-fuzz)',
      hoverBg: 'var(--color-ink)',
      hoverScale: 1.04,
      hoverOpacity: 1,
      pressedColor: 'var(--color-sun-red)',
      pressedBg: 'var(--color-ink)',
      pressedScale: 0.96,
      pressedTranslateY: 2,
      glowEnabled: true,
      glowCenter: 'var(--color-sunset-fuzz)',
      glowSpread: 45,
      glowFade: 85,
    },
  },
  {
    name: 'Deep Press',
    description: 'Heavy fill with dramatic press effect',
    state: {
      pat: 'fill-88',
      color: 'var(--color-ink)',
      bg: 'var(--color-cream)',
      scale: 2,
      hoverColor: 'var(--color-ink)',
      hoverBg: 'var(--color-sun-yellow)',
      hoverScale: 1.01,
      hoverOpacity: 1,
      pressedColor: 'var(--color-ink)',
      pressedBg: 'var(--color-sun-yellow)',
      pressedScale: 0.95,
      pressedTranslateY: 3,
      glowEnabled: true,
      glowCenter: 'var(--color-sun-yellow)',
      glowSpread: 50,
      glowFade: 90,
    },
  },
];

export const DEFAULT_STATE = PRESETS[0].state;
