import type { PlaygroundPreset } from './types';

export const PRESETS: PlaygroundPreset[] = [
  {
    name: 'Classic Ink',
    description: 'Ink on cream — the default RDNA look',
    state: {
      pat: 'checkerboard',
      color: 'var(--color-ink)',
      bg: 'transparent',
      scale: 2,
      glowEnabled: true,
      glowShape: 'circle',
      glowCenter: 'var(--color-sun-yellow)',
      glowMid: 'oklch(0.6 0.04 85)',
      glowBase: 'oklch(0.45 0.01 85)',
      glowRadius: 180,
      glowMidStop: 40,
    },
  },
  {
    name: 'Sun Glow',
    description: 'Yellow patterns with tight warm glow',
    state: {
      pat: 'diagonal-dots',
      color: 'var(--color-sun-yellow)',
      bg: 'var(--color-ink)',
      scale: 2,
      glowEnabled: true,
      glowShape: 'circle',
      glowCenter: 'var(--color-sun-yellow)',
      glowMid: 'oklch(0.7 0.06 90)',
      glowBase: 'oklch(0.35 0.02 85)',
      glowRadius: 120,
      glowMidStop: 35,
    },
  },
  {
    name: 'Neon Grid',
    description: 'Mint on ink — cyberpunk terminal',
    state: {
      pat: 'grid',
      color: 'var(--color-mint)',
      bg: 'var(--color-ink)',
      scale: 3,
      glowEnabled: true,
      glowShape: 'ellipse',
      glowCenter: 'var(--color-mint)',
      glowMid: 'oklch(0.5 0.05 160)',
      glowBase: 'oklch(0.3 0.01 160)',
      glowRadius: 200,
      glowMidStop: 45,
    },
  },
  {
    name: 'Cream Paper',
    description: 'Subtle texture for light backgrounds',
    state: {
      pat: 'dust',
      color: 'var(--color-ink)',
      bg: 'var(--color-cream)',
      scale: 1,
      glowEnabled: false,
      glowShape: 'circle',
      glowCenter: 'var(--color-sun-yellow)',
      glowMid: 'oklch(0.6 0.04 85)',
      glowBase: 'oklch(0.45 0.01 85)',
      glowRadius: 180,
      glowMidStop: 40,
    },
  },
  {
    name: 'Warm Spot',
    description: 'Sunset glow with wide elliptical spread',
    state: {
      pat: 'confetti',
      color: 'var(--color-ink)',
      bg: 'transparent',
      scale: 2,
      glowEnabled: true,
      glowShape: 'ellipse',
      glowCenter: 'var(--color-sunset-fuzz)',
      glowMid: 'oklch(0.55 0.05 60)',
      glowBase: 'oklch(0.4 0.02 60)',
      glowRadius: 250,
      glowMidStop: 50,
    },
  },
  {
    name: 'Deep Fill',
    description: 'Dense pattern with tight cursor spot',
    state: {
      pat: 'fill-88',
      color: 'var(--color-ink)',
      bg: 'var(--color-cream)',
      scale: 2,
      glowEnabled: true,
      glowShape: 'circle',
      glowCenter: 'var(--color-sun-yellow)',
      glowMid: 'oklch(0.65 0.06 85)',
      glowBase: 'oklch(0.5 0.01 85)',
      glowRadius: 100,
      glowMidStop: 30,
    },
  },
];

export const DEFAULT_STATE = PRESETS[0].state;
