
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * Greet someone by name - basic test command
 */
async greet(name: string) : Promise<string> {
    return await TAURI_INVOKE("greet", { name });
},
/**
 * Get the current application version
 */
async getVersion() : Promise<VersionInfo> {
    return await TAURI_INVOKE("get_version");
},
/**
 * Validate that a folder is a valid project (contains package.json or tsconfig.json)
 */
async validateProject(path: string) : Promise<ProjectValidation> {
    return await TAURI_INVOKE("validate_project", { path });
},
/**
 * Parse a single TSX component file and return component information
 */
async parseComponent(path: string) : Promise<Result<ComponentInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("parse_component", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Scan a directory for TSX components and return all found components
 */
async scanComponents(dir: string) : Promise<Result<ComponentInfo[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("scan_components", { dir }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Parse a CSS file and extract theme tokens from @theme blocks
 */
async parseTokens(cssPath: string) : Promise<Result<ThemeTokens, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("parse_tokens", { cssPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Scan a directory for design system violations
 */
async scanViolations(dir: string) : Promise<Result<ViolationInfo[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("scan_violations", { dir }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Detect violations in a single file
 */
async detectViolations(path: string) : Promise<Result<ViolationInfo[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("detect_violations", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Start watching a directory for file changes
 * Emits "file-changed" events to the frontend
 */
async startWatcher(path: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_watcher", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Stop the file watcher
 */
async stopWatcher() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_watcher") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get the currently watched path, if any
 */
async getWatchedPath() : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_watched_path") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

/**
 * Represents an extracted component with its metadata
 */
export type ComponentInfo = { name: string; file: string; line: number; props: PropInfo[]; defaultExport: boolean; unionTypes: UnionTypeInfo[] }
/**
 * Result of validating a project folder
 */
export type ProjectValidation = { valid: boolean; project_name: string | null; error: string | null }
/**
 * Represents a component prop with its type and optional default value
 */
export type PropInfo = { name: string; type: string; default?: string | null; doc?: string | null }
/**
 * Theme tokens extracted from @theme blocks
 */
export type ThemeTokens = { 
/**
 * Tokens from @theme inline (internal reference, not exported as utilities)
 */
inline: Partial<{ [key in string]: string }>; 
/**
 * Tokens from @theme (exported as Tailwind utilities)
 */
public: Partial<{ [key in string]: string }> }
/**
 * Represents a union type alias like `type ButtonVariant = 'primary' | 'secondary'`
 */
export type UnionTypeInfo = { name: string; values: string[]; line: number }
/**
 * Application version info returned by get_version command
 */
export type VersionInfo = { version: string; tauri_version: string }
/**
 * Represents a design system violation
 */
export type ViolationInfo = { file: string; line: number; column: number; severity: ViolationSeverity; message: string; codeSnippet: string; suggestion?: string | null }
/**
 * Violation severity levels
 */
export type ViolationSeverity = "warning" | "error"

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
