import type { RegistryEntry } from "./types";
import {
  ComposerShellDemo,
  AnnotationPinDemo,
  AnnotationDetailDemo,
  AnnotationListDemo,
  AnnotationBadgeDemo,
  ComposerShellV2Demo,
  AnnotationPinV2Demo,
  AnnotationDetailV2Demo,
  AnnotationListV2Demo,
  AnnotationBadgeV2Demo,
} from "./components/playground-ui-demos";

/**
 * App-local registry entries.
 *
 * Components here appear on the playground canvas alongside package components.
 * They use `packageName: "@rdna/radiants"` so they render in the same canvas
 * view — the `group` field separates them into their own section.
 */
export const appRegistry: RegistryEntry[] = [
  // ── Current (v1) ──────────────────────────────────────────────────────
  {
    id: "composershell",
    componentName: "ComposerShell",
    label: "ComposerShell.tsx",
    group: "Playground UI",
    packageName: "@rdna/radiants",
    Component: ComposerShellDemo as RegistryEntry["Component"],
    rawComponent: null,
    renderMode: "custom",
    defaultProps: {},
    sourcePath: "tools/playground/app/playground/components/ComposerShell.tsx",
  },
  {
    id: "annotationpin",
    componentName: "AnnotationPin",
    label: "AnnotationPin.tsx",
    group: "Playground UI",
    packageName: "@rdna/radiants",
    Component: AnnotationPinDemo as RegistryEntry["Component"],
    rawComponent: null,
    renderMode: "custom",
    defaultProps: {},
    sourcePath: "tools/playground/app/playground/components/AnnotationPin.tsx",
  },
  {
    id: "annotationbadge",
    componentName: "AnnotationBadge",
    label: "AnnotationBadge.tsx",
    group: "Playground UI",
    packageName: "@rdna/radiants",
    Component: AnnotationBadgeDemo as RegistryEntry["Component"],
    rawComponent: null,
    renderMode: "custom",
    defaultProps: {},
    sourcePath: "tools/playground/app/playground/components/AnnotationBadge.tsx",
  },
  {
    id: "annotationdetail",
    componentName: "AnnotationDetail",
    label: "AnnotationDetail.tsx",
    group: "Playground UI",
    packageName: "@rdna/radiants",
    Component: AnnotationDetailDemo as RegistryEntry["Component"],
    rawComponent: null,
    renderMode: "custom",
    defaultProps: {},
    sourcePath: "tools/playground/app/playground/components/AnnotationDetail.tsx",
  },
  {
    id: "annotationlist",
    componentName: "AnnotationList",
    label: "AnnotationList.tsx",
    group: "Playground UI",
    packageName: "@rdna/radiants",
    Component: AnnotationListDemo as RegistryEntry["Component"],
    rawComponent: null,
    renderMode: "custom",
    defaultProps: {},
    sourcePath: "tools/playground/app/playground/components/AnnotationList.tsx",
  },

  // ── Refined (v2) ─────────────────────────────────────────────────────
  {
    id: "composershell-v2",
    componentName: "ComposerShellV2",
    label: "ComposerShell v2",
    group: "Playground UI — Refined",
    packageName: "@rdna/radiants",
    Component: ComposerShellV2Demo as RegistryEntry["Component"],
    rawComponent: null,
    renderMode: "custom",
    defaultProps: {},
    sourcePath: "tools/playground/app/playground/components/refined/ComposerShellV2.tsx",
  },
  {
    id: "annotationpin-v2",
    componentName: "AnnotationPinV2",
    label: "AnnotationPin v2",
    group: "Playground UI — Refined",
    packageName: "@rdna/radiants",
    Component: AnnotationPinV2Demo as RegistryEntry["Component"],
    rawComponent: null,
    renderMode: "custom",
    defaultProps: {},
    sourcePath: "tools/playground/app/playground/components/refined/AnnotationPinV2.tsx",
  },
  {
    id: "annotationbadge-v2",
    componentName: "AnnotationBadgeV2",
    label: "AnnotationBadge v2",
    group: "Playground UI — Refined",
    packageName: "@rdna/radiants",
    Component: AnnotationBadgeV2Demo as RegistryEntry["Component"],
    rawComponent: null,
    renderMode: "custom",
    defaultProps: {},
    sourcePath: "tools/playground/app/playground/components/refined/AnnotationBadgeV2.tsx",
  },
  {
    id: "annotationdetail-v2",
    componentName: "AnnotationDetailV2",
    label: "AnnotationDetail v2",
    group: "Playground UI — Refined",
    packageName: "@rdna/radiants",
    Component: AnnotationDetailV2Demo as RegistryEntry["Component"],
    rawComponent: null,
    renderMode: "custom",
    defaultProps: {},
    sourcePath: "tools/playground/app/playground/components/refined/AnnotationDetailV2.tsx",
  },
  {
    id: "annotationlist-v2",
    componentName: "AnnotationListV2",
    label: "AnnotationList v2",
    group: "Playground UI — Refined",
    packageName: "@rdna/radiants",
    Component: AnnotationListV2Demo as RegistryEntry["Component"],
    rawComponent: null,
    renderMode: "custom",
    defaultProps: {},
    sourcePath: "tools/playground/app/playground/components/refined/AnnotationListV2.tsx",
  },
];
